import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { randomBytes } from "node:crypto";
import { mkdirSync, mkdtempSync, rmSync } from "node:fs";
import { createServer } from "node:net";
import { tmpdir } from "node:os";
import path from "node:path";
import { DatabaseSync } from "node:sqlite";
import { fileURLToPath, pathToFileURL } from "node:url";
import jwt from "../../server/node_modules/jsonwebtoken/index.js";

const root = fileURLToPath(new URL("../../", import.meta.url));
const temporary = mkdtempSync(path.join(tmpdir(), "ktga-conversations-"));
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ? pathToFileURL(process.env.PLAYWRIGHT_MODULE).href : "playwright");
const port = async () => {
  const probe = createServer();
  await new Promise((resolve) => probe.listen(0, "127.0.0.1", resolve));
  const value = probe.address().port;
  await new Promise((resolve) => probe.close(resolve));
  return value;
};
const apiPort = await port();
const webPort = await port();
const origin = `http://127.0.0.1:${webPort}`;
const apiOrigin = `http://127.0.0.1:${apiPort}`;
const secret = randomBytes(32).toString("hex");
const token = (id) => jwt.sign({ id, guest: false, sessionVersion: 0 }, secret, { expiresIn: "1h" });
const users = ["alpha", "beta", "gamma", "delta", "admin"].map((id) => ({
  id, pseudo: id, email: `${id}@example.com`, guest: false, active: true, admin: id === "admin",
  tokens: 10000, passwordPolicyVersion: 1, emailVerifiedAt: new Date().toISOString(),
  profile: { displayName: id, birthDate: "2000-01-01" },
  friends: id === "alpha" ? ["beta", "gamma", "delta"] : ["alpha"], friendRequests: { incoming: [], outgoing: [] }
}));
const database = new DatabaseSync(path.join(temporary, "main.sqlite"));
users.push({ ...users[0], id: "epsilon", pseudo: "epsilon", email: "epsilon@example.com", profile: { displayName: "epsilon", birthDate: "2000-01-01" }, friends: [] });
database.exec("CREATE TABLE users(id TEXT PRIMARY KEY,data TEXT NOT NULL,pseudo TEXT NOT NULL,email TEXT,guest INTEGER NOT NULL DEFAULT 0); CREATE TABLE rooms(id TEXT PRIMARY KEY,code TEXT NOT NULL UNIQUE,game_id TEXT NOT NULL,is_public INTEGER NOT NULL DEFAULT 1,finished INTEGER NOT NULL DEFAULT 0,created_at TEXT,data TEXT NOT NULL);");
for (const user of users) database.prepare("INSERT INTO users VALUES(?,?,?,?,0)").run(user.id, JSON.stringify(user), user.pseudo, user.email);
const room = { id: "chat-table", code: "CHAT01", name: "Table de test", gameId: "yahtzee", ownerId: "alpha", players: users.slice(0, 2), stake: 10, isPublic: true, finished: false, state: null, readyPlayerIds: [] };
database.prepare("INSERT INTO rooms VALUES(?,?,?,1,0,?,?)").run(room.id, room.code, room.gameId, new Date().toISOString(), JSON.stringify(room));
database.close();
const processes = [];
let serverOutput = "";
function start(args, cwd, env) {
  const child = spawn(process.execPath, args, { cwd, env: { ...process.env, ...env }, windowsHide: true, stdio: ["ignore", "pipe", "pipe"] });
  child.stdout.on("data", (chunk) => { serverOutput += chunk; });
  child.stderr.on("data", (chunk) => { serverOutput += chunk; });
  processes.push(child);
  return child;
}
const waitFor = async (check, label) => {
  const deadline = Date.now() + 25000;
  while (Date.now() < deadline) {
    try { if (await check()) return; } catch { /* Server or UI is still starting. */ }
    await new Promise((resolve) => setTimeout(resolve, 100));
  }
  throw new Error(`Timed out: ${label}\n${serverOutput.slice(-3000)}`);
};
const request = async (id, endpoint, body, method = "POST") => {
  const response = await fetch(`${apiOrigin}${endpoint}`, { method, headers: { Authorization: `Bearer ${token(id)}`, "Content-Type": "application/json" }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
  const result = await response.json();
  assert.ok(response.ok, `${endpoint}: ${response.status} ${JSON.stringify(result)}`);
  return result;
};
let browser;
try {
  start(["src/index.js"], path.join(root, "server"), {
    NODE_ENV: "test", PORT: String(apiPort), HOST: "127.0.0.1", JWT_SECRET: secret,
    CLIENT_ORIGIN: origin, CLIENT_DIST: "", APP_BASE_PATH: "", HTTPS_KEY_PATH: "", HTTPS_CERT_PATH: "", HTTPS_PFX_PATH: "",
    SMTP_HOST: "", EMAIL_FROM: "", PUBLIC_APP_URL: `${apiOrigin}/api/health`, SQLITE_PATH: path.join(temporary, "main.sqlite"),
    ...Object.fromEntries(["PARENTAL_DB_PATH", "TRIBUNAL_DB_PATH", "CHAT_DB_PATH", "STATUS_DB_PATH", "PATCHNOTES_DB_PATH", "REQUEST_LOG_PATH"].map((key) => [key, path.join(temporary, `${key}.sqlite`)]))
  });
  start(["node_modules/vite/bin/vite.js", "--host", "127.0.0.1", "--port", String(webPort), "--strictPort"], path.join(root, "client"), {
    VITE_API_URL: apiOrigin, VITE_SOCKET_URL: apiOrigin, VITE_SOCKET_PATH: "/socket.io", VITE_BASE_PATH: "/"
  });
  await waitFor(async () => (await fetch(`${apiOrigin}/api/health`)).ok && (await fetch(origin)).ok, "isolated servers");
  browser = await chromium.launch({ channel: "msedge", headless: true });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, hasTouch: true });
  await context.addCookies([{ name: "ktga_session", value: token("alpha"), url: apiOrigin, httpOnly: true, sameSite: "Lax" }]);
  await context.addInitScript(() => {
    localStorage.setItem("ktga-privacy-choice", JSON.stringify({ version: "2026-09-27", chosenAt: Date.now(), enabled: false }));
    window.chatToneCount = 0;
    const original = AudioContext.prototype.createOscillator;
    AudioContext.prototype.createOscillator = function (...args) { window.chatToneCount += 1; return original.apply(this, args); };
  });
  const page = await context.newPage();
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  if (process.env.BLOCKER_MODULE) {
    const { PlaywrightBlocker } = await import(pathToFileURL(process.env.BLOCKER_MODULE).href);
    const blocker = await PlaywrightBlocker.fromPrebuiltAdsAndTracking(fetch);
    await blocker.enableBlockingInPage(page);
  }
  await page.goto(origin);
  const toggle = page.locator(".conversation-toggle");
  const drawer = page.locator(".conversation-drawer");
  const contacts = () => page.locator('.conversation-contact-strip [role="tab"]');
  await toggle.waitFor();
  await toggle.click();
  await page.getByRole("button", { name: "Amis", exact: true }).click();
  assert.equal(await contacts().count(), 0, "friends without an opened conversation stay hidden");
  await page.getByRole("button", { name: "Fermer Social", exact: true }).click();
  await request("beta", "/api/chat/messages", { channelType: "direct", friendId: "alpha", content: "Bonjour alpha" });
  await waitFor(async () => await toggle.locator(".conversation-toggle-count").textContent() === "1", "private unread badge");
  await waitFor(async () => await page.evaluate(() => window.chatToneCount) === 2, "private notification sound");
  await toggle.click();
  await waitFor(async () => await contacts().count() === 1 && await contacts().first().locator(".display-name-text").innerText() === "beta", "only beta conversation visible");
  await waitFor(async () => await toggle.locator(".conversation-toggle-count").count() === 0, "visible message acknowledged");
  let profileRequests = 0;
  page.on("request", (entry) => { if (/\/api\/users\/[^/]+\/public/.test(entry.url())) profileRequests += 1; });
  await contacts().first().locator(".display-name").click();
  await page.waitForTimeout(400);
  assert.equal(profileRequests, 0, "conversation nickname does not open public profile");
  await page.getByRole("button", { name: "Choisir un ami", exact: true }).click();
  await page.getByRole("button", { name: "Discuter avec gamma", exact: true }).click();
  await waitFor(async () => await contacts().count() === 2, "explicit empty conversation opened");
  assert.equal(await contacts().first().locator(".display-name-text").innerText(), "beta", "recent messages sort before empty conversations");
  await waitFor(async () => (await request("alpha", "/api/chat/unread", undefined, "GET")).channels.find((row) => row.friendId === "gamma")?.opened, "empty conversation saved");
  await page.reload();
  await toggle.waitFor();
  await toggle.click();
  await page.getByRole("button", { name: /^Amis/ }).click();
  await waitFor(async () => await contacts().count() === 2, "empty conversation persists across reload");
  await request("gamma", "/api/chat/messages", { channelType: "direct", friendId: "alpha", content: "Salut depuis gamma" });
  await waitFor(async () => (await contacts().first().innerText()).startsWith("gamma"), "latest conversation first");
  const previews = path.join(root, "docs", "previews");
  mkdirSync(previews, { recursive: true });
  await page.screenshot({ path: path.join(previews, "chat-conversations-desktop.png"), fullPage: true });
  await page.reload();
  await toggle.waitFor();
  await toggle.click();
  await page.getByRole("button", { name: /^Amis/ }).click();
  await waitFor(async () => await contacts().count() === 2, "conversations persist across reload");
  assert.equal(await contacts().filter({ hasText: "delta" }).count(), 0, "unopened friend remains absent");
  await page.goto(`${origin}/table/CHAT01`);
  await toggle.waitFor();
  await waitFor(async () => (await request("alpha", "/api/chat/unread?roomCode=CHAT01", undefined, "GET")).channels.some((row) => row.channelType === "room"), "room access");
  await toggle.click();
  await page.getByRole("button", { name: "Table", exact: true }).waitFor({ state: "visible" });
  await page.getByRole("button", { name: "Fermer Social", exact: true }).click();
  await request("beta", "/api/chat/messages", { channelType: "room", roomCode: "CHAT01", content: "Bienvenue a la table" });
  await waitFor(async () => await toggle.locator(".conversation-toggle-count").textContent() === "1", "table unread badge");
  await waitFor(async () => await page.evaluate(() => window.chatToneCount) === 2, "table notification sound");
  await toggle.click();
  await page.getByRole("button", { name: /^Table 1/ }).click();
  await page.getByText("Bienvenue a la table", { exact: true }).waitFor();
  await page.waitForTimeout(800);
  const rich = await request("beta", "/api/chat/messages", { channelType: "room", roomCode: "CHAT01", content: "**Un guide** https://www.ktga.me/profil\nhttps://www.ktga.me/table/CHAT01\n@!ktga-dice-4 @!ktga-card-AH @!ktga-rank-diamant3\n# Un titre\n![Image](https://www.ktga.me/favicon.svg)" });
  const richRow = page.locator(".conversation-message").filter({ hasText: "Un guide" });
  await richRow.locator(".conversation-route-link").first().waitFor();
  assert.equal(await richRow.locator(".conversation-route-link").count(), 2);
  assert.ok(await richRow.getByRole("link", { name: /Table de alpha/ }).isVisible());
  assert.equal(await richRow.locator("strong").filter({ hasText: "Un guide" }).count(), 1);
  assert.equal(await richRow.locator("h1, img").count(), 0, "chat headings and images never render");
  assert.equal(await richRow.locator(".ktga-inline-dice .pip").count(), 4);
  assert.equal(await richRow.locator(".ktga-inline-card .playing-card").count(), 1);
  await richRow.getByRole("img", { name: "Diamant III" }).waitFor();
  assert.equal(rich.links.find((link) => link.kind === "table").label, "Table de alpha");
  await page.waitForTimeout(800);
  const blocked = await fetch(`${apiOrigin}/api/chat/messages`, { method: "POST", headers: { Authorization: `Bearer ${token("beta")}`, "Content-Type": "application/json" }, body: JSON.stringify({ channelType: "room", roomCode: "CHAT01", content: "https://evil.example/phishing" }) });
  assert.equal(blocked.status, 400);
  await page.screenshot({ path: path.join(previews, "chat-rich-content-desktop.png"), fullPage: false });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: path.join(previews, "chat-rich-content-mobile.png"), fullPage: false });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1), false);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await richRow.getByRole("link", { name: "Profil", exact: true }).click();
  await page.waitForURL(`${origin}/profil`, { timeout: 5000 });
  await page.goBack();
  await page.getByRole("button", { name: "Table", exact: true }).click();
  await richRow.getByRole("link", { name: "Profil", exact: true }).waitFor();
  await page.getByRole("button", { name: "Passer en fenêtre", exact: true }).click();
  await richRow.getByRole("link", { name: "Profil", exact: true }).click();
  await page.waitForURL(`${origin}/profil`, { timeout: 5000 });
  await page.goBack();
  await page.getByRole("button", { name: "Table", exact: true }).click();
  await richRow.getByRole("link", { name: /Table de alpha/ }).waitFor();
  const roomLink = await richRow.getByRole("link", { name: /Table de alpha/ }).getAttribute("href");
  assert.equal(roomLink, "https://www.ktga.me/table/CHAT01");
  await page.setViewportSize({ width: 390, height: 844 });
  await richRow.getByRole("link", { name: "Profil", exact: true }).tap();
  await page.waitForURL(`${origin}/profil`, { timeout: 5000 });
  await page.goBack();
  await page.getByRole("button", { name: "Table", exact: true }).click();
  await page.setViewportSize({ width: 1440, height: 1000 });
  const beforeDrag = await drawer.boundingBox();
  const handle = await page.locator(".conversation-drag-handle").boundingBox();
  await page.mouse.move(handle.x + handle.width / 2, handle.y + handle.height / 2);
  await page.mouse.down();
  await page.mouse.move(handle.x + handle.width / 2 + 40, handle.y + handle.height / 2 + 30, { steps: 5 });
  await page.mouse.up();
  const afterDrag = await drawer.boundingBox();
  assert.ok(afterDrag.x > beforeDrag.x + 30 && afterDrag.y > beforeDrag.y + 20, "floating chat remains movable");
  await page.getByRole("button", { name: "Attacher à droite", exact: true }).click();
  await waitFor(async () => await toggle.locator(".conversation-toggle-count").count() === 0, "table message acknowledged");
  await page.getByRole("button", { name: "Couper le son du chat", exact: true }).click();
  const tones = await page.evaluate(() => window.chatToneCount);
  await page.getByRole("button", { name: "Fermer Social", exact: true }).click();
  await page.waitForTimeout(800);
  await request("beta", "/api/chat/messages", { channelType: "room", roomCode: "CHAT01", content: "Message silencieux" });
  await waitFor(async () => await toggle.locator(".conversation-toggle-count").textContent() === "1", "silent message remains unread");
  assert.equal(await page.evaluate(() => window.chatToneCount), tones, "sound preference respected");
  await toggle.click();
  await page.getByText("Message silencieux", { exact: true }).waitFor();
  await waitFor(async () => await toggle.locator(".conversation-toggle-count").count() === 0, "silent message acknowledged");
  await page.screenshot({ path: path.join(previews, "chat-alerts-desktop.png"), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.waitForTimeout(700);
  assert.ok(await drawer.isVisible(), "drawer survives content blocking on mobile");
  await page.screenshot({ path: path.join(previews, "chat-alerts-mobile.png"), fullPage: true });
  await request("alpha", "/api/connections/muted/beta", {});
  await page.waitForTimeout(800);
  await request("beta", "/api/chat/messages", { channelType: "room", roomCode: "CHAT01", content: "Message masque" });
  await page.waitForTimeout(400);
  assert.equal(await page.getByText("Message masque", { exact: true }).count(), 0, "muted messages are not delivered");
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole("button", { name: /^Amis/ }).click();
  await page.getByRole("button", { name: "Choisir un ami", exact: true }).click();
  const friendRows = page.locator(".connections-content .player-network-row");
  const betaRow = friendRows.filter({ has: page.getByRole("button", { name: "Discuter avec beta", exact: true }) });
  await betaRow.getByText("Hors ligne", { exact: true }).waitFor();
  const betaContext = await browser.newContext();
  await betaContext.addCookies([{ name: "ktga_session", value: token("beta"), url: apiOrigin, httpOnly: true, sameSite: "Lax" }]);
  await betaContext.addInitScript(() => localStorage.setItem("ktga-privacy-choice", JSON.stringify({ version: "2026-09-27", chosenAt: Date.now(), enabled: false })));
  const betaPage = await betaContext.newPage();
  await betaPage.goto(origin);
  await betaPage.locator(".conversation-toggle").waitFor();
  await page.bringToFront();
  await betaRow.getByText("En ligne", { exact: true }).waitFor();
  assert.ok(await betaRow.locator(".friend-presence-dot.is-online").isVisible(), "online indicator survives Ghostery");
  assert.equal(await friendRows.first().getByRole("button", { name: "Discuter avec beta", exact: true }).count(), 1, "online friends sort first");
  const secondBetaPage = await betaContext.newPage();
  await secondBetaPage.goto(origin);
  await secondBetaPage.locator(".conversation-toggle").waitFor();
  await betaPage.close();
  await page.bringToFront();
  await page.waitForTimeout(5500);
  assert.equal(await betaRow.getByText("En ligne", { exact: true }).count(), 1, "closing one tab does not mark a friend offline");
  await page.screenshot({ path: path.join(previews, "friends-presence-desktop.png"), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.ok(await betaRow.locator(".friend-presence-dot.is-online").isVisible());
  const identityLayout = await betaRow.evaluate((row) => {
    const identity = row.querySelector(".friend-identity").getBoundingClientRect();
    const actions = row.querySelector(".player-network-actions").getBoundingClientRect();
    const label = row.querySelector(".display-name-text").getBoundingClientRect();
    return { stacked: identity.bottom <= actions.top, labelWidth: label.width, contained: actions.right <= row.getBoundingClientRect().right };
  });
  assert.ok(identityLayout.stacked && identityLayout.contained && identityLayout.labelWidth > 20, "mobile identity and controls do not overlap");
  await page.screenshot({ path: path.join(previews, "friends-presence-mobile.png"), fullPage: true });
  await betaContext.close();
  await betaRow.getByText("Hors ligne", { exact: true }).waitFor();
  await page.getByRole("dialog", { name: "Amis", exact: true }).getByRole("button", { name: "Fermer", exact: true }).click();
  const requestAt = Date.now();
  await request("epsilon", "/api/friends/request", { userId: "alpha" });
  await page.locator(".achievement-toast").filter({ hasText: "epsilon" }).waitFor();
  assert.ok(Date.now() - requestAt < 3000, "friend request arrives without waiting for polling");
  await page.getByRole("button", { name: "Notifications", exact: true }).click();
  const friendNotice = page.locator(".notification-friend-request").filter({ hasText: "epsilon" });
  await friendNotice.getByRole("button", { name: "Accepter", exact: true }).waitFor();
  await friendNotice.getByRole("button", { name: "Ignorer", exact: true }).click();
  await waitFor(async () => (await request("alpha", "/api/friends", undefined, "GET")).incoming.some((row) => row.id === "epsilon"), "ignored request remains pending");
  const invitationRoom = await request("beta", "/api/rooms", { gameId: "421", stake: 10, name: "Invitation instantanee" });
  const invitationAt = Date.now();
  await request("beta", `/api/rooms/${invitationRoom.code}/invite`, { friendId: "alpha" });
  const inviteNotice = page.locator(".notification-room-invite").filter({ hasText: "Invitation instantanee" });
  await inviteNotice.getByRole("button", { name: "Accepter", exact: true }).waitFor();
  assert.ok(Date.now() - invitationAt < 3000, "room invite arrives without waiting for polling");
  assert.equal(await inviteNotice.getByRole("button", { name: "Accepter", exact: true }).isEnabled(), true);
  await inviteNotice.getByRole("button", { name: "Refuser", exact: true }).click();
  const otherInbox = await request("gamma", "/api/notifications", undefined, "GET");
  assert.equal(otherInbox.some((row) => row.roomCode === invitationRoom.code), false, "invitations are scoped to the recipient");
  const sanction = { login: "delta@example.com", tokens: 10000, moderation: { softBan: { active: true, reason: "Test sanction temporaire", endsAt: new Date(Date.now() + 86400000).toISOString() } } };
  await request("admin", "/api/admin/users/delta", sanction, "PATCH");
  const sanctioned = await request("admin", "/api/admin/users/delta", undefined, "GET");
  assert.deepEqual(sanctioned.tribunal.behavior, { score: 95, cases: 1, sanctions: 1 });
  await request("admin", "/api/admin/users/delta", sanction, "PATCH");
  const unchanged = await request("admin", "/api/admin/users/delta", undefined, "GET");
  assert.deepEqual(unchanged.tribunal.behavior, sanctioned.tribunal.behavior, "resaving does not penalize twice");
  const register = await request("admin", "/api/admin/tribunal", undefined, "GET");
  assert.equal(register.cases.filter((entry) => entry.source === "administrative-49-3" && entry.accusedId === "delta").length, 1);
  await request("gamma", "/api/chat/messages", { channelType: "global", content: "https://www.ktga.me/table/CHAT01\nhttps://www.ktga.me/table/GONE01\nhttps://www.ktga.me/bugs/1842\nhttps://www.ktga.me/patchnotes?version=0.1.0\nhttps://www.ktga.me/patchnotes/0.2.1" });
  await page.goto(`${origin}/profil`);
  await toggle.waitFor();
  await toggle.click();
  await page.getByRole("button", { name: "Global", exact: true }).click();
  await page.locator(".conversation-feed").getByRole("link", { name: /BUG 1842/ }).waitFor();
  assert.equal(await page.locator(".conversation-feed").getByRole("link", { name: /Partie terminée/ }).count(), 0);
  assert.equal(await page.locator(".conversation-route-ended").count(), 1);
  assert.equal(await page.locator(".conversation-feed").getByRole("link", { name: /Patchnote 0.2.1/ }).getAttribute("href"), "https://www.ktga.me/patchnotes?version=0.2.1");
  await page.locator(".conversation-feed").getByRole("link", { name: /Patchnote 0.1.0/ }).click();
  await page.waitForURL(`${origin}/patchnotes?version=0.1.0`);
  await page.goBack();
  await page.getByRole("button", { name: "Global", exact: true }).click();
  await page.locator(".conversation-feed").getByRole("link", { name: /Table de alpha/ }).click();
  await page.waitForURL(`${origin}/table/CHAT01`, { timeout: 5000 });
  await page.goto(`${origin}/profil`);
  await toggle.waitFor();
  await toggle.click();
  await page.getByRole("button", { name: "Global", exact: true }).click();
  await page.locator(".conversation-feed").getByRole("link", { name: /Table de alpha/ }).waitFor();
  await request("alpha", "/api/rooms/CHAT01", undefined, "DELETE");
  await waitFor(async () => await page.locator(".conversation-route-ended").count() === 2, "existing table link becomes inactive on closure");
  assert.equal(await page.locator(".conversation-feed").getByRole("link", { name: /Table de alpha|Partie terminée/ }).count(), 0);
  await page.screenshot({ path: path.join(previews, "chat-closed-table-links-desktop.png"), fullPage: false });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: path.join(previews, "chat-closed-table-links-mobile.png"), fullPage: false });
  assert.deepEqual(errors, []);
  console.log("PASS: chat links navigate by mouse and touch, docked/floating, and preserve dragging and table identifiers.");
  console.log("PASS: closed tables lose their link live; bug IDs and patchnote versions are displayed, and version navigation retains its query.");
  console.log("PASS: opened conversations, recent order, persistence, nickname selection, private/table sound and badges, mute, desktop/mobile.");
  console.log(process.env.BLOCKER_MODULE ? "PASS: Ghostery content blocking enabled throughout the browser checks." : "NOTE: content blocking not requested; set BLOCKER_MODULE to test it.");
  console.log("PASS: temporary administrative sanction lowers behavior once and creates a 49,3 tribunal record.");
  console.log("PASS: online friends, multiple tabs, disconnect grace, desktop/mobile, instant invitations and recipient isolation.");
} finally {
  await browser?.close();
  for (const child of processes) {
    if (child.exitCode !== null) continue;
    await new Promise((resolve) => { child.once("exit", resolve); child.kill(); });
  }
  if (path.dirname(temporary) === path.resolve(tmpdir()) && path.basename(temporary).startsWith("ktga-conversations-")) rmSync(temporary, { recursive: true, force: true });
}
