import assert from "node:assert/strict";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { achievementRuleSchemas } from "../../server/src/services/achievement-rules.js";

const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ? pathToFileURL(process.env.PLAYWRIGHT_MODULE).href : "playwright");
const output = mkdtempSync(path.join(tmpdir(), "ktga-pagination-"));
const base = process.env.CASINO_TEST_URL ?? "http://127.0.0.1:5173";
const user = { id: "p85", pseudo: "Admin", admin: true, guest: false, tokens: 100000, cosmetics: { equipped: {} }, profile: {}, profileStats: {}, achievements: { unlocked: [] } };
const shop = Array.from({ length: 55 }, (_, index) => ({ id: `custom-item-${index}`, type: "icons", category: index < 45 ? "classic" : "premium", value: `test-${index}`, name: `Objet ${String(index + 1).padStart(3, "0")}`, description: "Objet de collection", price: 500, ...(index < 8 ? { packs: ["japanese-traditional"] } : index < 16 ? { packs: ["neon"] } : {}) }));
const users = Array.from({ length: 65 }, (_, index) => ({ id: `user${index}`, login: `login${index}`, displayName: `Joueur ${String(index + 1).padStart(3, "0")}`, active: true, tokens: 1000, gamesPlayed: 3, wins: 1 }));
const achievements = Array.from({ length: 37 }, (_, index) => ({ id: `achievement-${index}`, title: `Succes ${String(index + 1).padStart(3, "0")}`, description: "Un objectif", group: "Site", type: "site", target: 1, enabled: true, rule: { source: "metric", metric: "wins" } }));
const ranks = Array.from({ length: 100 }, (_, index) => ({ id: `p${index + 1}`, rank: index + 1, value: 10000 - index, games: 20, user: { id: `p${index + 1}`, pseudo: `Place ${index + 1}`, cosmetics: {}, profile: {}, profileStats: {} } }));
const browser = await chromium.launch({ channel: "msedge", headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = [];
page.on("pageerror", (error) => errors.push(error.message));
await page.addInitScript(() => localStorage.setItem("ktga-privacy-choice", JSON.stringify({ version: "2026-09-27", chosenAt: Date.now(), enabled: false })));
await page.route("**/*", async (route) => {
  const url = new URL(route.request().url());
  if (url.pathname.includes("socket.io")) return route.fulfill({ status: 503, body: "" });
  const offset = url.pathname.indexOf("/api/");
  if (offset < 0) return route.continue();
  const endpoint = url.pathname.slice(offset);
  const send = (json) => route.fulfill({ json, headers: { "access-control-allow-origin": "*", "access-control-allow-methods": "GET,POST,PATCH,DELETE", "access-control-allow-headers": "authorization,content-type" } });
  if (route.request().method() === "OPTIONS") return route.fulfill({ status: 204 });
  if (endpoint === "/api/me") return send(user);
  if (endpoint === "/api/config") return send({ siteName: "KTGA", guestAccessEnabled: true });
  if (endpoint === "/api/me/statistics") return send({});
  if (endpoint === "/api/shop") return send(shop);
  if (endpoint === "/api/achievements") return send(achievements);
  if (endpoint === "/api/admin") return send({ users, shop, achievements, games: [], overview: {}, settings: {}, pricing: {}, permissions: { manageAchievements: true, editBuiltInShopItems: true }, achievementRuleSchemas: achievementRuleSchemas([], shop) });
  if (endpoint === "/api/leaderboards") return send({ rows: ranks, total: 110, self: ranks[84], games: [], seasons: ["2026-Q3"], period: { currentSeason: "2026-Q3" }, balanceAt: "2026-09-27" });
  return send([]);
});
const pager = (name) => page.getByRole("navigation", { name });
const noOverflow = async () => assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
try {
  await page.goto(`${base}/shop`);
  await page.locator(".shop-grid .shop-item").nth(11).waitFor();
  assert.equal(await page.locator(".shop-grid .shop-item").count(), 12);
  await pager("Pages de la boutique").getByRole("button", { name: "Page suivante" }).click();
  assert.match(await page.locator(".shop-grid .shop-item").first().textContent(), /Objet 013/);
  await pager("Pages de la boutique").getByRole("button", { name: "Dernière page" }).click();
  assert.equal(await page.locator(".shop-grid .shop-item").count(), 9);
  await page.locator(".shop-subselector").getByRole("button", { name: "Premium", exact: true }).click();
  assert.match(await pager("Pages de la boutique").textContent(), /Page 1 \/ 1/);
  await page.getByRole("button", { name: "Packs", exact: true }).click();
  await page.locator(".pack-theme-tabs").waitFor();
  assert.equal(await page.locator(".pack-theme-tabs button:not(.active)").first().evaluate((element) => getComputedStyle(element).color), "rgb(246, 233, 201)");
  await page.screenshot({ path: path.join(output, "packs-desktop.png"), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 }); await noOverflow();
  await page.screenshot({ path: path.join(output, "packs-mobile.png"), fullPage: true });
  await page.getByRole("button", { name: "Objets", exact: true }).click();
  await page.locator(".shop-subselector").getByRole("button", { name: "Classique", exact: true }).click();
  await pager("Pages de la boutique").getByRole("button", { name: "Page suivante" }).click();
  await pager("Pages de la boutique").scrollIntoViewIfNeeded(); await noOverflow();
  await page.screenshot({ path: path.join(output, "shop-pagination-mobile.png") });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(`${base}/admin`);
  await page.locator(".admin-nav").getByRole("button", { name: /Boutique/ }).click();
  await page.locator(".admin-table tbody tr").nth(19).waitFor();
  assert.equal(await page.locator(".admin-table tbody tr").count(), 20);
  await pager("Pages de la boutique admin").getByRole("button", { name: "Dernière page" }).click();
  assert.equal(await page.locator(".admin-table tbody tr").count(), 15);
  await page.getByPlaceholder("Nom, description ou identifiant").fill("Objet 055");
  assert.equal(await page.locator(".admin-table tbody tr").count(), 1);
  assert.match(await pager("Pages de la boutique admin").textContent(), /Page 1 \/ 1/);
  await page.locator(".admin-nav").getByRole("button", { name: /Joueurs/ }).click();
  await pager("Pages des joueurs").getByRole("button", { name: "Page suivante" }).click();
  assert.match(await page.locator(".admin-table tbody tr").first().textContent(), /Joueur 021/);
  await pager("Pages des joueurs").getByLabel("Éléments par page").selectOption("50");
  assert.equal(await page.locator(".admin-table tbody tr").count(), 50);
  await page.locator(".admin-nav").getByRole("button", { name: /Succès/ }).click();
  assert.equal(await page.locator(".achievement-admin-grid > article").count(), 12);
  await pager("Pages des succès admin").getByRole("button", { name: "Dernière page" }).click();
  assert.equal(await page.locator(".achievement-admin-grid > article").count(), 1);
  await page.getByPlaceholder("Nom, identifiant, jeu ou groupe").fill("missing");
  assert.match(await pager("Pages des succès admin").textContent(), /Aucun résultat/);
  await page.getByPlaceholder("Nom, identifiant, jeu ou groupe").fill("");
  await page.setViewportSize({ width: 390, height: 844 });
  await pager("Pages des succès admin").scrollIntoViewIfNeeded(); await noOverflow();
  await page.screenshot({ path: path.join(output, "admin-pagination-mobile.png") });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(`${base}/classements`);
  await page.locator(".leaderboard-table tbody tr").nth(19).waitFor();
  assert.match(await page.locator(".leaderboard-table tfoot").textContent(), /votre position/);
  await pager("Pages du classement").getByRole("button", { name: "Dernière page" }).click();
  assert.match(await page.locator(".leaderboard-table tbody tr").first().textContent(), /^81/);
  assert.equal(await page.locator(".leaderboard-table tfoot").count(), 0);
  await page.getByRole("tab", { name: "Victoires", exact: true }).click();
  await page.locator(".leaderboard-table tbody tr").nth(19).waitFor();
  assert.match(await pager("Pages du classement").textContent(), /Page 1 \/ 5/);
  await page.screenshot({ path: path.join(output, "leaderboard-desktop.png"), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 }); await noOverflow();
  await pager("Pages du classement").scrollIntoViewIfNeeded();
  await page.screenshot({ path: path.join(output, "leaderboard-mobile.png") });
  assert.deepEqual(errors, []);
  console.log(`Pagination checks passed. Screenshots: ${output}`);
} finally { await browser.close(); }
