import { useEffect, useState } from "react";
import { BadgeCheck, CalendarDays, Eye, KeyRound, Mail, Save, ShieldCheck, Star, UserRound } from "lucide-react";
import { PasswordField } from "../common/PasswordField.jsx";
import { DataRequestPanel } from "./DataRequestPanel.jsx";
import { AccountSecurity } from "./AccountSecurity.jsx";
import { localDate } from "../../utils/dates.js";
import { publicProfileStatOptions } from "../../config/site.js";
import { ageFromBirthDate, memberStatOptions } from "../../utils/presentation.jsx";
import "./account-workspace.css";

export function AccountWorkspace({ user, form, setForm, favorites, games, toggleFavorite, statForm, setStatForm, milestones, onPreview, onSave, onSaveEmail, onSavePassword, saving, onUser, onError, onMessage }) {
  const [tab, setTab] = useState("identity");
  const [confirmation, setConfirmation] = useState("");
  useEffect(() => { if (!form.password) setConfirmation(""); }, [form.password]);
  const change = (key) => (event) => setForm((current) => ({ ...current, [key]: event.target.value }));
  const save = (event) => { event.preventDefault(); onSave(); };
  return <div className="account-workspace">
    <header className="account-workspace-heading"><div><span className="eyebrow">Paramètres personnels</span><h2>Mon compte</h2></div><button type="button" className="secondary" onClick={onPreview}><Eye size={17} />Profil public</button></header>
    <nav className="account-workspace-tabs" aria-label="Réglages du compte">{[["identity", "Mon profil", UserRound], ["visibility", "Carte et confidentialité", Eye], ["security", "Connexion et sécurité", ShieldCheck]].map(([key, label, Icon]) => <button type="button" key={key} className={tab === key ? "active" : ""} aria-current={tab === key ? "page" : undefined} onClick={() => setTab(key)}><Icon size={17} />{label}</button>)}</nav>
    {user.guest ? <p>Les paramètres sont réservés aux comptes joueurs.</p> : <>
      {tab === "identity" && <form onSubmit={save} className="account-workspace-form">
        <section className="account-workspace-section"><header><UserRound size={19} /><h3>Identité publique</h3><span>Visible par les joueurs</span></header>
          <div className="account-workspace-row"><label htmlFor="account-display-name">Pseudo en jeu</label><div><input id="account-display-name" name="nickname" autoComplete="nickname" required minLength={3} maxLength={32} value={form.displayName} onChange={change("displayName")} /></div></div>
          <div className="account-workspace-row"><label htmlFor="account-biography">Bio</label><div><textarea id="account-biography" value={form.bio} onChange={change("bio")} maxLength={180} rows={4} placeholder="Quelques mots sur toi" /><small className="account-workspace-counter">{form.bio.length} / 180</small></div></div>
        </section>
        <section className="account-workspace-section"><header><CalendarDays size={19} /><h3>Informations personnelles</h3></header><div className="account-workspace-row"><label htmlFor="account-birth-date">Date de naissance<small>La date complète est privée.</small></label><div className="account-workspace-date"><input id="account-birth-date" type="date" max={localDate()} autoComplete="bday" value={form.birthDate} onChange={change("birthDate")} disabled={Boolean(user.profile?.birthDate)} />{form.birthDate && <span>{ageFromBirthDate(form.birthDate)} ans</span>}{user.profile?.birthDate && <small>Une correction peut être demandée à l’administration.</small>}</div></div>
          <div className="account-workspace-row"><label htmlFor="account-gender">Genre<small>Facultatif</small></label><select id="account-gender" value={form.gender} onChange={change("gender")}>{["", "Homme", "Femme", "Non-binaire", "Autre", "Préfère ne pas dire"].map((gender) => <option value={gender} key={gender}>{gender || "Non renseigné"}</option>)}</select></div>
        </section>
        <section className="account-workspace-section"><header><Star size={19} /><h3>Mes jeux favoris</h3><span>{favorites.length} / 5</span></header><div className="favorite-game-grid">{games.map((game) => <button type="button" key={game.id} className={favorites.includes(game.id) ? "favorite-game active" : "favorite-game"} aria-pressed={favorites.includes(game.id)} onClick={() => toggleFavorite(game.id)} disabled={!favorites.includes(game.id) && favorites.length >= 5}>{game.name}</button>)}</div></section>
        <div className="account-workspace-actions"><button type="submit" disabled={Boolean(saving)}><Save size={17} />{saving === "profile" ? "Enregistrement…" : "Enregistrer le profil"}</button></div>
      </form>}
      {tab === "visibility" && <><form onSubmit={save} className="account-workspace-form"><section className="account-workspace-section"><header><BadgeCheck size={19} /><h3>Statistiques de la member card</h3></header>
        {[0, 1].map((index) => {
          const selected = statForm.memberCardStats[index] === "overallWinRate" ? "winRate" : statForm.memberCardStats[index] ?? "hidden";
          return <div className="account-workspace-row" key={index}><label htmlFor={`account-stat-${index}`}>Emplacement {index + 1}</label><div><select id={`account-stat-${index}`} value={selected} onChange={(event) => { const memberCardStats = [...statForm.memberCardStats]; memberCardStats[index] = event.target.value; setStatForm({ ...statForm, memberCardStats }); }}>{memberStatOptions().map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>{selected === "customAchievement" && <div className="account-workspace-custom"><label htmlFor={`account-custom-${index}`}>Succès personnalisé</label><select id={`account-custom-${index}`} value={statForm.customAchievementIds[index] ?? ""} onChange={(event) => { const ids = [...statForm.customAchievementIds]; ids[index] = event.target.value; setStatForm({ ...statForm, customAchievementIds: ids }); }}><option value="">Choisir un milestone</option>{milestones.map((entry) => <option key={entry.id} value={entry.id}>{entry.title}</option>)}</select></div>}</div></div>;
        })}</section><section className="account-workspace-section"><header><Eye size={19} /><h3>Indicateurs du profil public</h3></header><div className="account-workspace-visibility">{publicProfileStatOptions.map(([key, label]) => <label key={key}><span>{label}</span><input type="checkbox" checked={statForm.visibleProfileStats.includes(key)} onChange={(event) => setStatForm({ ...statForm, visibleProfileStats: event.target.checked ? [...new Set([...statForm.visibleProfileStats, key])] : statForm.visibleProfileStats.filter((entry) => entry !== key) })} /></label>)}</div></section><div className="account-workspace-actions"><button type="submit" disabled={Boolean(saving)}><Save size={17} />Enregistrer l’affichage</button></div></form><DataRequestPanel userId={user.id} /></>}
      {tab === "security" && <div className="account-workspace-form"><section className="account-workspace-section"><header><Mail size={19} /><h3>Adresse de connexion</h3><span className={user.emailVerified ? "is-verified" : ""}>{user.emailVerified ? "Vérifiée" : "À vérifier"}</span></header><form className="account-workspace-row" onSubmit={(event) => { event.preventDefault(); onSaveEmail(); }}><label htmlFor="account-email">Adresse email<small>Privée</small></label><div><input id="account-email" required type="email" autoComplete="email" value={form.login} onChange={change("login")} /><button type="submit" className="secondary account-workspace-email-action" disabled={Boolean(saving) || !form.login || form.login === user.login && user.emailVerified}><Mail size={16} />{form.login === user.login ? "Renvoyer la vérification" : "Modifier l’adresse"}</button></div></form></section>
        <section className="account-workspace-section"><header><KeyRound size={19} /><h3>Mot de passe</h3></header><form className="account-workspace-password" onSubmit={(event) => { event.preventDefault(); if (form.password === confirmation) onSavePassword(); }}><PasswordField label="Nouveau mot de passe" autoComplete="new-password" minLength={10} maxLength={128} required value={form.password} onChange={change("password")} /><small>10 caractères minimum, une lettre, un chiffre, une majuscule et un caractère spécial.</small><PasswordField label="Confirmer le nouveau mot de passe" autoComplete="new-password" required value={confirmation} onChange={(event) => setConfirmation(event.target.value)} feedback={confirmation ? { matches: form.password === confirmation } : null} /><button type="submit" className="secondary" disabled={Boolean(saving) || !form.password || form.password !== confirmation}><KeyRound size={17} />Modifier le mot de passe</button></form></section>
        <section className="account-workspace-section"><header><ShieldCheck size={19} /><h3>Double authentification</h3></header><AccountSecurity user={user} onUser={onUser} onError={onError} onMessage={onMessage} /></section>
      </div>}
    </>}
  </div>;
}
