const faq = (id, title, body) => ({ id: `faq-ranked-${id}`, kind: "faq", category: "Mode classé", title, body, image: "", imageAlt: "", published: true });

export const rankedFaqEntries = [
  faq("classic", "Quelle est la différence entre Classique et Classé ?", "Le mode **Classique** permet d'organiser vos tables et de choisir leurs options. Le mode **Classé** vous place dans une file qui réunit des joueurs pour une partie aux règles communes.\n\nLe classé possède des **rangs et des divisions propres à chaque jeu**. Il ne remplace ni vos niveaux, ni vos maîtrises, ni les parties entre amis."),
  faq("games", "Quels jeux proposent un mode classé ?", "Le classé est proposé pour **Belote, Texas Hold'em, Président, Liar's Dice, Velvet Ruse, Yahtzee et Dés de Minuit**.\n\nSur l'accueil, choisissez **Classé** pour retrouver les jeux concernés. Leur disponibilité et leurs règles peuvent être ajustées par l'administration ; consultez les informations de la file avant de rejoindre."),
  faq("join", "Comment lancer une partie classée ?", "Connectez-vous avec un compte enregistré, choisissez **Classé** sur l'accueil, puis **Rejoindre le classé** sur le jeu qui vous intéresse. La fenêtre présente les règles et permet de **rejoindre la file**.\n\nVous n'avez pas à créer une table ni à désigner un hôte : le site prépare la partie lorsque le groupe est prêt. Vous ne pouvez rechercher qu'une partie à la fois ; terminez une partie en cours avant de rejoindre la file."),
  faq("placements", "Pourquoi suis-je indiqué « Non classé » ?", "Vous êtes encore en **placement** pour ce jeu. Jouez les parties demandées : votre progression est affichée sous la forme **parties effectuées / parties nécessaires**.\n\nLe rang est révélé à la fin de cette étape, en tenant compte de vos résultats et des adversaires rencontrés. Le nombre de placements dépend des réglages du jeu. Une partie annulée pour un problème technique ne compte pas comme un placement ; un abandon reste une défaite."),
  faq("divisions", "Dans quel ordre progressent les rangs et les divisions ?", "Les rangs suivent cet ordre :\n\n**Bois → Cuivre → Bronze → Argent → Or → Platine → Diamant → Maître → Grand Maître → Légende**.\n\nDu Bois au Maître, la progression est **I → II → III**, puis la division I du rang suivant. Par exemple, **Argent III est supérieur à Argent II**, et **Or I vient après Argent III**.\n\nGrand Maître et Légende n'ont pas de divisions dans la configuration actuelle."),
  faq("per-game", "Mon rang est-il partagé entre tous les jeux ?", "Non. Chaque jeu possède **son propre placement et son propre rang**. Une bonne progression au Yahtzee ne vous attribue pas automatiquement le même rang à la Belote.\n\nVous pouvez donc être classé sur un jeu et encore en placement sur un autre."),
  faq("waiting", "Pourquoi la recherche de partie prend-elle parfois du temps ?", "La file cherche d'abord des joueurs de divisions proches, puis élargit progressivement sa recherche. L'attente dépend aussi du jeu et du nombre de personnes disponibles.\n\nSi le jeu accepte plusieurs tailles de groupe, la file essaie d'abord de **remplir la table**. Après le délai prévu, elle peut proposer une partie avec le nombre minimum de joueurs requis.\n\nPendant un placement, la recherche est plus large et peut s'adapter si aucun groupe compatible n'est trouvé. Le temps affiché et les silhouettes indiquent l'avancement ; rester dans la file ne signifie pas que vous avez déjà pris place dans une table."),
  faq("ready", "Une partie a été trouvée : que dois-je faire ?", "Cliquez sur **Accepter et rejoindre** pendant le délai indiqué. Les silhouettes passent du gris au vert lorsque les joueurs confirment.\n\nLe temps de préparation laisse à chacun l'occasion de voir la proposition. Quand les confirmations et la préparation sont terminées, **« Création de la table… »** annonce la transition vers la partie. Ne créez pas une autre table entre-temps."),
  faq("missing-ready", "Que se passe-t-il si un joueur ne confirme pas ?", "La proposition expire si tous les joueurs n'ont pas confirmé à temps. Les joueurs qui restent disponibles peuvent repartir en recherche pour former un nouveau groupe.\n\nLa partie n'est pas lancée avec un siège réservé à quelqu'un qui n'a pas accepté. Pour le poker, la cave n'est engagée qu'au moment où la table est effectivement créée."),
  faq("leave-queue", "Puis-je quitter la file sans abandonner une partie ?", "Oui, utilisez **Quitter la file** tant que la table n'a pas été créée. Vous quittez la recherche ou la proposition en attente ; ce n'est pas un abandon d'une partie lancée.\n\nUne fois entré dans la partie, quitter la table relève des règles d'abandon du classé. Fermer seulement la fenêtre de recherche peut la laisser fonctionner en arrière-plan : utilisez bien le bouton pour vous retirer."),
  faq("results", "Qu'est-ce qui fait monter ou descendre mon rang ?", "Le rang évolue selon les **résultats de vos parties classées** et l'opposition rencontrée. Votre position finale et les égalités sont prises en compte ; à la Belote, le résultat de l'équipe compte.\n\nGagner contre une opposition plus forte peut faire davantage progresser. Une défaite, un abandon ou une absence prolongée peuvent faire reculer selon les règles appliquées.\n\nLe récapitulatif de fin de partie montre votre évolution. Une seule victoire ne garantit pas de passer immédiatement à la division suivante."),
  faq("levels", "Mon niveau ou ma maîtrise me donne-t-il un meilleur rang ?", "Non. **Les niveaux et les maîtrises suivent votre progression d'expérience**, tandis que le rang dépend de vos parties classées.\n\nChanger de titre, obtenir un succès ou gagner une maîtrise ne vous fait pas automatiquement monter de division. Les deux progressions peuvent avancer en parallèle, sans se remplacer."),
  faq("tokens", "Faut-il miser des jetons pour jouer en classé ?", "Les jeux classés ne demandent pas de mise lorsque les jetons ne font pas partie de leur fonctionnement. Leurs informations de table mettent alors en avant les **rangs**.\n\n**Le Texas Hold'em garde une cave et ses règles de mises** : vérifiez les informations de la file et votre solde avant d'accepter. Les jetons restent exclusivement virtuels, comme partout sur le site."),
  faq("bots", "Les bots peuvent-ils compléter une table classée ?", "Non. Les tables classées sont formées avec des **joueurs disposant d'un compte enregistré**. Un bot ne vient pas remplir une place manquante ni remplacer un adversaire pour le classement.\n\nPour jouer avec des bots ou choisir librement vos variantes, utilisez le mode Classique lorsque le jeu le permet."),
  faq("timers", "Que faire si le temps de mon tour expire ou si je suis déconnecté ?", "Surveillez le **compteur de tour** : une action automatique peut être appliquée lorsque le délai est dépassé. Les règles et délais sont indiqués dans les informations de la file.\n\nAprès une coupure, revenez sur le site et dans votre table dès que possible, pendant le délai de reconnexion. Une absence prolongée ou un départ volontaire peuvent compter comme un abandon ou entraîner une pénalité selon les règles du jeu.\n\nSi le problème vient du site, signalez-le avec le jeu, le contexte et les étapes utiles. N'incluez pas de codes de connexion dans le signalement."),
  faq("insignia", "Comment afficher un insigne de classement sur mon profil ?", "Dans **Profil → Compte**, choisissez l'insigne du jeu classé que vous souhaitez porter, puis enregistrez votre profil. Il s'affiche **à gauche de votre icône cosmétique**.\n\nVous pouvez conserver votre style et votre titre en même temps. Le titre vient de la progression en niveaux et maîtrises ; l'insigne représente votre rang dans le jeu choisi."),
  faq("spectator", "Puis-je regarder une partie classée sans y participer ?", "Oui, **lorsque les règles autorisent les spectateurs**, rejoindre une table classée déjà lancée permet de la regarder.\n\nVous voyez les actions et informations publiques, pas les mains ni les choix privés. Vous n'occupez pas de place dans le groupe classé et l'observation ne compte pas comme une partie de placement. Pour participer au classé, passez par sa file de recherche.")
];

const scenario = (question, options, answerId, explanation) => ({ question, options: options.map((text, index) => ({ id: String(index + 1), text })), answerId: String(answerId), explanation });

export const progressionGuideEntries = [
  {
    id: "guide-game-levels", kind: "guide", category: "Niveaux et maîtrises", published: true,
    title: "Tes niveaux, jeu par jeu",
    lead: "Une partie perdue n'est pas forcément du temps perdu : ton expérience continue d'avancer.",
    body: "### Une progression pour chaque jeu\n\nUne **partie terminée** rapporte de l'expérience dans le jeu concerné. Une victoire peut ajouter un bonus ; certains succès donnent aussi de l'XP. Les gains dépendent des réglages du jeu.\n\nDans **Profil → Compte**, la progression de tes **jeux favoris** affiche ton niveau, ton titre et la barre vers le prochain palier. Un jeu manque ? Ajoute-le à tes favoris.\n\n### Un titre qui te ressemble\n\nLes niveaux débloquent des titres. Avec **Titre affiché**, choisis l'un de ceux que tu possèdes, même s'il ne correspond pas à ton dernier palier, ou décide de ne pas en afficher.\n\nLes jetons servent aux mises et à la personnalisation ; l'XP sert à la progression. **Ce ne sont pas la même chose.**",
    image: "/guides/game-levels.png", imageAlt: "Exemple de progression au Yahtzee : niveau, titre et barre d'expérience vers le prochain niveau.",
    challenge: scenario("Tu termines une partie sans gagner. Ton expérience peut-elle quand même avancer ?", ["Oui, une partie terminée peut rapporter de l'XP", "Non, seules les victoires font progresser", "Seulement si je change de pseudo"], 1, "La fin de partie rapporte l'XP prévue pour ce jeu, même sans victoire. Une victoire peut ajouter un bonus ; les récompenses de certains succès peuvent aussi t'aider.")
  },
  {
    id: "guide-game-masteries", kind: "guide", category: "Niveaux et maîtrises", published: true,
    title: "Après le niveau 100, une nouvelle maîtrise",
    lead: "Tu connais bien ton jeu ? Un nouveau cycle t'attend, sans effacer ce que tu as accompli.",
    body: "### Un nouveau départ, pas une remise à zéro\n\nQuand tu atteins le **niveau 101**, tu reviens au **niveau 1** avec une **maîtrise supplémentaire** dans ce jeu. Ton expérience totale, tes succès et tes titres débloqués restent conservés.\n\nChaque maîtrise demande davantage d'expérience pour monter de niveau : le coût du cycle normal est multiplié par **(maîtrise + 1)**.\n\n### Le chiffre romain à côté du titre\n\nÀ maîtrise 0, aucun chiffre n'est ajouté. Ensuite viennent **I, II, III, IV…**\n\nPar exemple, **Brelan** devient **Brelan I** à maîtrise 1, ou **Brelan IV** à maîtrise 4. Tu peux toujours choisir un titre déjà débloqué.\n\nUn succès obtenu n'est pas remis en jeu à chaque cycle : **ses récompenses ne sont attribuées qu'une fois**. La maîtrise reste distincte de ton rang classé.",
    image: "/guides/game-masteries.png", imageAlt: "Exemple au Yahtzee : niveau 10, maîtrise IV et titre Brelan IV.",
    challenge: scenario("Tu atteins le niveau 101 pour la première fois. Que se passe-t-il ?", ["Je perds mes titres et mes succès", "Je reviens niveau 1 avec une maîtrise et je garde mes acquis", "Je deviens automatiquement Légende en classé"], 2, "Tu gagnes ta première maîtrise et recommences au niveau 1, sans perdre tes titres ni tes succès. Ce nouveau cycle demande plus d'XP ; il ne change pas automatiquement ton rang classé.")
  },
  {
    id: "guide-ranked-play", kind: "guide", category: "Mode classé", published: true,
    title: "Prêt à essayer le classé ?",
    lead: "Même jeu, autre défi : ici, le site prépare la table et tout le monde confirme avant de commencer.",
    body: "### Trouver ta prochaine table\n\nSur l'accueil, passe de **Classique** à **Classé**, choisis un jeu, puis rejoins sa file. La recherche privilégie les divisions proches et essaie de remplir le groupe. Tu peux quitter avec **Quitter la file** tant que la table n'est pas créée.\n\n### Confirmer, puis jouer\n\nLorsqu'une partie est trouvée, utilise **Accepter et rejoindre** pendant le délai indiqué. Les silhouettes deviennent vertes quand les joueurs sont prêts. Le message **« Création de la table… »** annonce ensuite le passage à la partie.\n\nPendant le jeu, regarde le **compteur de tour**. Un abandon ou une absence prolongée peuvent pénaliser ta progression ; mieux vaut lancer une recherche quand tu as le temps de jouer.\n\n### Des placements, puis un rang\n\nAu début, tu es **Non classé** pour ce jeu. Termine les placements demandés pour découvrir ton rang. La progression va du **Bois** à la **Légende** ; les divisions suivent **I → II → III** avant le rang suivant. Chaque jeu garde son propre classement.\n\nDans ton profil, tu peux porter un insigne de rang à côté de ton icône. **Ton rang, ton titre et ta maîtrise racontent des progressions différentes.**",
    image: "/guides/ranked-confirmation.png", imageAlt: "Proposition d'une partie classée au Yahtzee : temps de préparation, confirmations des joueurs et bouton Accepter et rejoindre.",
    challenge: scenario("La partie a été trouvée, mais ta silhouette est encore grise. Quel est le bon réflexe ?", ["Attendre sans rien faire", "Cliquer sur Accepter et rejoindre avant la fin du délai", "Créer ma propre table à côté"], 2, "La silhouette verte signifie que tu as confirmé. Chacun doit accepter : le site prépare ensuite la table. Si une confirmation manque à l'expiration, le groupe ne démarre pas avec une place vide.")
  }
];

export function withProgressionHelp(document) {
  const entries = [...document.entries];
  const titleKey = (entry) => `${entry.kind}:${entry.title.normalize("NFKC").toLocaleLowerCase("fr").replaceAll("’", "'").trim()}`;
  function insertMissing(additions, after) {
    const ids = new Set(entries.map((entry) => entry.id)), titles = new Set(entries.map(titleKey));
    const missing = additions.filter((entry) => !ids.has(entry.id) && !titles.has(titleKey(entry))).map((entry) => structuredClone(entry));
    entries.splice(after + 1, 0, ...missing);
  }
  const progressIndex = entries.findIndex((entry) => entry.id === "guide-progress");
  insertMissing(progressionGuideEntries, progressIndex >= 0 ? progressIndex : entries.findLastIndex((entry) => entry.kind === "guide"));
  const tablesIndex = entries.findLastIndex((entry) => entry.kind === "faq" && entry.category === "Tables");
  insertMissing(rankedFaqEntries, tablesIndex >= 0 ? tablesIndex : entries.length - 1);
  return { ...document, entries };
}
