import { useCallback, useEffect, useState } from "react";
import { Bug, CheckCheck, ExternalLink, Link2, Plus, RefreshCw, Save, Search, Trash2 } from "lucide-react";
import { api } from "../../api.js";
import { appPath } from "../../navigation/routes.js";
import { Dialog } from "../../components/common/Dialog.jsx";
import { ConfirmActionButton } from "../../components/common/ConfirmAction.jsx";
import { Pagination } from "../../components/feedback/Feedback.jsx";
import { BugImage, BugReportDetail, issueDate } from "./BugReportDetail.jsx";

const request = (path, method, body) => api(path, { method, body: JSON.stringify(body) });
function Select({ label, value, onChange, options, empty }) {
  return <label>{label}<select aria-label={label} value={value ?? ""} onChange={(event) => onChange(event.target.value)}>{empty && <option value="">{empty}</option>}{Object.entries(options ?? {}).map(([key, text]) => <option value={key} key={key}>{text}</option>)}</select></label>;
}
function TreatmentFields({ draft, setDraft, metadata, bulk = false }) {
  const change = (key, value) => setDraft((current) => ({ ...current, [key]: value }));
  metadata = { ...metadata, statuses: Object.fromEntries(Object.entries(metadata?.statuses ?? {}).filter(([key]) => key !== "deleted" || metadata?.canDelete)) };
  return <><div className="issue-fields"><Select label="Statut" value={draft.status} onChange={(value) => change("status", value)} options={metadata?.statuses} empty={bulk ? "Ne pas modifier" : undefined} /><Select label="Priorité" value={draft.priority} onChange={(value) => change("priority", value)} options={metadata?.priorities} empty={bulk ? "Ne pas modifier" : undefined} />{!bulk && <Select label="Catégorie" value={draft.category} onChange={(value) => change("category", value)} options={metadata?.categories} />}<Select label="Assignation" value={draft.assignee} onChange={(value) => change("assignee", value)} options={{ ...(bulk ? { none: "Retirer l'assignation" } : {}), ...Object.fromEntries((metadata?.staff ?? []).map((user) => [user.id, user.name])) }} empty={bulk ? "Ne pas modifier" : "Non assigné"} /><Select label="Groupe" value={draft.groupId} onChange={(value) => change("groupId", value)} options={{ ...(bulk ? { none: "Retirer le groupe" } : {}), ...Object.fromEntries((metadata?.groups ?? []).map((group) => [group.id, group.name])) }} empty={bulk ? "Ne pas modifier" : "Sans groupe"} /><label className="issue-wide">Note interne<textarea aria-label="Note interne" maxLength={4000} rows={3} value={draft.internalNote ?? ""} onChange={(event) => change("internalNote", event.target.value)} /></label><label className="issue-wide">Réponse au joueur<textarea aria-label="Réponse au joueur" maxLength={4000} rows={3} value={draft.response ?? ""} onChange={(event) => change("response", event.target.value)} /></label></div><label className="issue-check"><input type="checkbox" checked={draft.responsePublic ?? false} onChange={(event) => change("responsePublic", event.target.checked)} />Publier cette réponse (sans donnée personnelle)</label></>;
}
export function BugReportsAdmin() {
  const [metadata, setMetadata] = useState(null), [result, setResult] = useState(null), [editing, setEditing] = useState(null);
  const [filters, setFilters] = useState({ search: "", status: "all", priority: "all", category: "all", visibility: "all", assignee: "", group: "", page: 1, pageSize: 20 });
  const [selected, setSelected] = useState([]), [bulk, setBulk] = useState(false), [changes, setChanges] = useState({}), [groupName, setGroupName] = useState("");
  const [error, setError] = useState(""), [busy, setBusy] = useState(false), [loading, setLoading] = useState(true);
  const load = useCallback(async () => {
    setLoading(true);
    try { setMetadata(await api("/api/admin/bugs/metadata", { background: true })); setResult(await api(`/api/admin/bugs?${new URLSearchParams(filters)}`, { background: true })); setError(""); }
    catch (reason) { setError(reason.message); }
    finally { setLoading(false); }
  }, [filters]);
  useEffect(() => { const timer = setTimeout(load, 180); return () => clearTimeout(timer); }, [load]);
  function filter(key, value) { setFilters((current) => ({ ...current, [key]: value, page: 1 })); setSelected([]); }
  async function applyBatch() {
    setBusy(true); setError("");
    try {
      const payload = Object.fromEntries(Object.entries(changes).filter(([, value]) => value !== "").map(([key, value]) => [key, value === "none" ? "" : value]));
      if (!Object.keys(payload).length) throw new Error("Choisis au moins une modification.");
      await request("/api/admin/bugs/batch", "POST", { ids: selected, changes: payload }); setBulk(false); setSelected([]); setChanges({}); await load();
    } catch (reason) { setError(reason.message); }
    finally { setBusy(false); }
  }
  async function addGroup(event) {
    event.preventDefault(); setBusy(true);
    try { await request("/api/admin/bugs/groups", "POST", { name: groupName }); setGroupName(""); await load(); }
    catch (reason) { setError(reason.message); }
    finally { setBusy(false); }
  }
  return <section className="card admin-list issue-admin"><div className="issue-section-heading"><div><span className="eyebrow">Diagnostic et suivi</span><h2><Bug size={22} />Signalements de bugs</h2><p className="issue-muted">{metadata?.summary.pending ?? 0} à traiter · {metadata?.summary.private ?? 0} dossiers privés</p></div><button type="button" className="secondary icon-toggle" title="Actualiser" onClick={load}><RefreshCw size={18} /></button></div>
    {error && <p className="error" role="alert">{error}</p>}<div className="issue-filters"><label className="issue-search"><Search size={17} /><input aria-label="Rechercher un signalement" value={filters.search} placeholder="Titre ou identifiant" onChange={(event) => filter("search", event.target.value)} /></label>{[["status", "Statut", metadata?.statuses], ["priority", "Priorité", metadata?.priorities], ["category", "Catégorie", metadata?.categories], ["visibility", "Visibilité", { public: "Public", private: "Privé" }]].map(([key, label, options]) => <Select key={key} label={label} value={filters[key]} onChange={(value) => filter(key, value)} options={{ all: "Tous", ...options }} />)}<Select label="Assignation" value={filters.assignee} onChange={(value) => filter("assignee", value)} options={Object.fromEntries((metadata?.staff ?? []).map((user) => [user.id, user.name]))} empty="Tous" /><Select label="Groupe" value={filters.group} onChange={(value) => filter("group", value)} options={Object.fromEntries((metadata?.groups ?? []).map((group) => [group.id, group.name]))} empty="Tous" /></div>
    <div className="issue-bulk-toolbar"><span>{selected.length} sélectionné(s)</span><button type="button" className="secondary" disabled={!selected.length} onClick={() => { setChanges({}); setBulk(true); }}><CheckCheck size={16} />Modifier en série</button><form className="actions" onSubmit={addGroup}><input aria-label="Nom du groupe" placeholder="Nouveau groupe" minLength={3} maxLength={120} required value={groupName} onChange={(event) => setGroupName(event.target.value)} /><button type="submit" className="secondary icon-toggle" disabled={busy} title="Créer le groupe"><Plus size={17} /></button></form></div>
    {loading ? <p role="status">Chargement des dossiers…</p> : <div className="issue-admin-table"><table className="score-table"><thead><tr><th><input type="checkbox" aria-label="Sélectionner cette page" checked={Boolean(result?.rows.length && result.rows.every((row) => selected.includes(row.id)))} onChange={(event) => setSelected(event.target.checked ? result.rows.map((row) => row.id) : [])} /></th><th>Dossier</th><th>Statut / priorité</th><th>Assignation</th><th>Publication</th><th>Actions</th></tr></thead><tbody>{result?.rows.map((row) => <tr key={row.id}><td><input type="checkbox" aria-label={`Sélectionner ${row.code}`} checked={selected.includes(row.id)} onChange={() => setSelected((current) => current.includes(row.id) ? current.filter((entry) => entry !== row.id) : [...current, row.id].slice(0, 100))} /></td><td><strong>{row.code} · {row.title}</strong><small>{metadata?.categories[row.category]} · {issueDate(row.created_at)}</small></td><td><span className={`issue-state issue-state-${row.status}`}>{metadata?.statuses[row.status]}</span><small>{metadata?.priorities[row.priority]}</small></td><td>{metadata?.staff.find((user) => user.id === row.assignee)?.name ?? "Non assigné"}<small>{metadata?.groups.find((group) => group.id === row.group_id)?.name}</small></td><td>{row.visible ? "Public" : "Privé"}<small>{row.pending_comments ? `${row.pending_comments} commentaire(s) à relire` : ""}</small></td><td><button type="button" className="secondary" onClick={() => setEditing(row.id)}>Ouvrir</button></td></tr>)}</tbody></table>{!result?.rows.length && <p className="issue-empty">Aucun signalement.</p>}</div>}{result && <Pagination {...result} onPage={(page) => { setFilters({ ...filters, page }); setSelected([]); }} onPageSize={(pageSize) => { setFilters({ ...filters, pageSize, page: 1 }); setSelected([]); }} />}
    {editing && <BugEditor id={editing} onClose={() => setEditing(null)} onChanged={load} />}
    {bulk && <Dialog title={`Modifier ${selected.length} signalements`} className="issue-editor-dialog" dismissible={!busy} onClose={() => setBulk(false)}><div className="issue-editor-body"><TreatmentFields draft={changes} setDraft={setChanges} metadata={metadata} bulk /><p className="issue-muted">Seuls les dossiers sélectionnés changent. Les relations et les publications ne sont pas modifiées.</p>{error && <p className="error" role="alert">{error}</p>}</div><div className="issue-editor-footer"><button type="button" disabled={busy} onClick={applyBatch}><CheckCheck size={17} />Appliquer aux dossiers sélectionnés</button></div></Dialog>}
  </section>;
}

export function BugEditor({ id, onClose, onChanged }) {
  const [report, setReport] = useState(null), [metadata, setMetadata] = useState(null), [tab, setTab] = useState("report"), [draft, setDraft] = useState({});
  const [publication, setPublication] = useState({}), [relation, setRelation] = useState({ targetId: "", type: "related" }), [search, setSearch] = useState(""), [matches, setMatches] = useState([]);
  const [resolution, setResolution] = useState(null), [error, setError] = useState(""), [busy, setBusy] = useState(false), [saved, setSaved] = useState("");
  const load = useCallback(async (reset = false) => {
    const meta = await api("/api/admin/bugs/metadata", { background: true });
    const next = await api(`/api/admin/bugs/${id}`, { background: true });
    setMetadata(meta); setReport(next);
    if (reset) {
      setDraft({ status: next.status, priority: next.priority, category: next.category, assignee: next.assignee, groupId: next.groupId ?? "", internalNote: "", response: "", responsePublic: false });
      setPublication({ title: next.publicTitle || next.title, description: next.publicDescription || next.description, expected: next.publicExpected || (!next.visible ? next.expected : ""), actual: next.publicActual || (!next.visible ? next.actual : ""), steps: next.publicSteps || (!next.visible ? next.steps : ""), visible: next.visible, reviewed: false, imageIds: next.images.filter((image) => image.visible).map((image) => image.id) });
    }
  }, [id]);
  useEffect(() => { load(true).catch((reason) => setError(reason.message)); }, [load]);
  useEffect(() => {
    if (!search.trim()) { setMatches([]); return; }
    let cancelled = false;
    const timer = setTimeout(() => api(`/api/admin/bugs?${new URLSearchParams({ search, pageSize: 20 })}`, { background: true }).then((result) => { if (!cancelled) setMatches(result.rows.filter((row) => row.id !== Number(id))); }).catch(() => {}), 220);
    return () => { cancelled = true; clearTimeout(timer); };
  }, [search, id]);
  async function action(path, method, body, reset = false) {
    setBusy(true); setError(""); setSaved("");
    try { await request(`/api/admin/bugs/${id}${path}`, method, body); await load(reset); await onChanged?.(); setSaved("Modifications enregistrées."); return true; }
    catch (reason) { setError(reason.message); return false; }
    finally { setBusy(false); }
  }
  const toggleImage = (imageId) => setPublication((current) => ({ ...current, imageIds: current.imageIds.includes(imageId) ? current.imageIds.filter((entry) => entry !== imageId) : [...current.imageIds, imageId], reviewed: false }));
  return <Dialog title={`BUG ${id} · Dossier privé`} className="issue-editor-dialog" dismissible={!busy} onClose={onClose}>
    <nav className="issue-tabs" aria-label="Gestion du bug">{[["report", "Dossier"], ["treatment", "Traitement"], ["relations", "Relations"], ["publication", "Publication"], ["history", "Historique"]].map(([value, label]) => <button type="button" key={value} className={tab === value ? "active" : "secondary"} onClick={() => { setTab(value); setSaved(""); }}>{label}</button>)}</nav>
    <div className="issue-editor-body">{!report ? <p role="status">Chargement…</p> : <>
      {tab === "report" && <><h3>{report.title}</h3><p className="issue-muted">Compte : {report.reporterId || "Visiteur non connecté"}</p><BugReportDetail report={report} metadata={metadata} />{report.comments.filter((entry) => entry.kind !== "internal").map((entry) => <article className="issue-comment" key={entry.id}><header><strong>{entry.kind === "staff" ? "Équipe" : "Joueur"}</strong><time>{issueDate(entry.createdAt)}</time><button type="button" className="secondary" disabled={busy} onClick={() => action(`/comments/${entry.id}`, "PATCH", { visible: !entry.visible })}>{entry.visible ? "Masquer" : "Publier après relecture"}</button></header><p className="issue-prewrap">{entry.body}</p></article>)}</>}
      {tab === "treatment" && <><TreatmentFields draft={draft} setDraft={setDraft} metadata={metadata} /><p className="issue-muted">Pour proposer la résolution des dossiers liés, utilise « Résoudre et vérifier les liens ».</p></>}
      {tab === "relations" && <><h3>Relier un autre signalement</h3><div className="issue-fields"><label>Rechercher un dossier<input aria-label="Rechercher un dossier" value={search} placeholder="BUG 1842 ou titre" onChange={(event) => setSearch(event.target.value)} /></label><Select label="Type de relation" value={relation.type} onChange={(type) => setRelation({ ...relation, type })} options={metadata?.relations} /><label>Dossier principal / cible<input aria-label="Dossier principal / cible" value={relation.targetId} placeholder="1842" onChange={(event) => setRelation({ ...relation, targetId: event.target.value })} /></label></div><p className="issue-muted">Doublon et dépendance : ce dossier pointe vers le dossier choisi. Les relations similaires ou liées sont réciproques.</p><button type="button" disabled={busy || !relation.targetId} onClick={() => action("/relations", "POST", relation)}><Link2 size={16} />Ajouter la relation</button>{matches.map((row) => <p key={row.id}><button type="button" className="secondary" onClick={() => setRelation({ ...relation, targetId: row.id })}>BUG {row.id} · {row.title}</button></p>)}{report.suggestions.length > 0 && <section className="issue-text-section"><h3>Signalements potentiellement similaires</h3>{report.suggestions.map((row) => <p key={row.id}><button type="button" className="secondary" onClick={() => setRelation({ targetId: row.id, type: "similar" })}>BUG {row.id} · {row.title}</button></p>)}</section>}<h3>Relations existantes</h3><ul className="issue-linked-list">{report.links.map((link) => <li key={`${link.sourceId}-${link.targetId}-${link.type}`}><span>{metadata.relations[link.type]} {link.direction === "incoming" ? "(relation entrante)" : ""}</span><a href={appPath("bugs", link.id)} target="_blank" rel="noreferrer">BUG {link.id} · {link.title}</a><ConfirmActionButton className="secondary icon-toggle" title="Retirer la relation" dialogTitle="Retirer cette relation ?" message="Les dossiers restent conservés. Seul leur lien sera supprimé." confirmLabel="Retirer" onConfirm={async () => { if (!await action("/relations", "DELETE", link)) throw new Error("La relation n'a pas pu être retirée."); }}><Trash2 size={16} /></ConfirmActionButton></li>)}</ul></>}
      {tab === "publication" && <><p className="issue-privacy-note">Les diagnostics, l’identité, le contexte original et les notes internes restent privés. Relis ces textes et chaque capture : seules les informations sélectionnées seront publiques.</p><div className="issue-fields"><label className="issue-wide">Titre public<input aria-label="Titre public" maxLength={160} value={publication.title} onChange={(event) => setPublication({ ...publication, title: event.target.value, reviewed: false })} /></label><label className="issue-wide">Description publique<textarea aria-label="Description publique" rows={7} maxLength={6000} value={publication.description} onChange={(event) => setPublication({ ...publication, description: event.target.value, reviewed: false })} /></label>
        {[["expected", "Résultat attendu public", 3000], ["actual", "Résultat obtenu public", 3000], ["steps", "Étapes pour reproduire publiques", 5000]].map(([key, label, limit]) => <label key={key} className={key === "steps" ? "issue-wide" : ""}>{label}<textarea aria-label={label} rows={3} maxLength={limit} value={publication[key] ?? ""} onChange={(event) => setPublication({ ...publication, [key]: event.target.value, reviewed: false })} /></label>)}
      </div><div className="issue-section-heading"><h3>Captures publiques : {publication.imageIds.length} / {report.images.length}</h3><div className="actions"><button type="button" className="secondary" onClick={() => setPublication({ ...publication, imageIds: report.images.map((image) => image.id), reviewed: false })}>Tout sélectionner</button><button type="button" className="secondary" onClick={() => setPublication({ ...publication, imageIds: [], reviewed: false })}>Tout masquer</button></div></div><div className="issue-image-grid">{report.images.map((image) => <figure key={image.id}><BugImage image={image} reportId={report.id} /><figcaption><label className="issue-check"><input type="checkbox" checked={publication.imageIds.includes(image.id)} onChange={() => toggleImage(image.id)} />Publier cette capture</label><small>{publication.imageIds.includes(image.id) ? "Visible publiquement après enregistrement" : "Capture privée"}</small></figcaption></figure>)}</div><label className="issue-check"><input type="checkbox" checked={publication.visible} onChange={(event) => setPublication({ ...publication, visible: event.target.checked })} />Publier le contenu relu du bug</label><label className="issue-check"><input type="checkbox" checked={publication.reviewed} onChange={(event) => setPublication({ ...publication, reviewed: event.target.checked })} />J’ai vérifié les textes et les captures sélectionnées ; ils ne contiennent aucune information sensible.</label></>}
      {tab === "history" && <>{report.comments.filter((entry) => entry.kind === "internal").map((entry) => <article key={entry.id} className="issue-comment"><strong>Note interne · {issueDate(entry.createdAt)}</strong><p className="issue-prewrap">{entry.body}</p></article>)}{report.actions.map((entry, index) => <article key={index} className="issue-comment"><header><strong>{entry.kind}</strong><time>{issueDate(entry.created_at)}</time></header><p className="issue-prewrap">{entry.body}</p></article>)}</>}
    </>}{error && <p className="error" role="alert">{error}</p>}{saved && <p role="status">{saved}</p>}</div>
    <div className="issue-editor-footer"><a className="secondary button-link" href={appPath("bugs", id)} target="_blank" rel="noreferrer"><ExternalLink size={16} />Page de suivi</a>{metadata?.canDelete && report?.status !== "deleted" && <ConfirmActionButton className="secondary danger-icon" title="Supprimer ce bug" dialogTitle={`Supprimer BUG ${id} ?`} message="Le dossier et ses captures disparaîtront du suivi public. L’historique restera accessible dans l’administration et le dossier pourra être restauré." confirmLabel="Supprimer le dossier" danger disabled={busy || !report} onConfirm={async () => { if (!await action("", "DELETE", {}, true)) throw new Error("Suppression impossible."); }}><Trash2 size={17} />Supprimer</ConfirmActionButton>}<button type="button" className="secondary" disabled={busy || !report || report.status === "deleted"} onClick={() => setResolution({ status: "fixed", linkedIds: report.resolutionPlan.rows.filter((row) => row.suggested).map((row) => row.id), response: "" })}><CheckCheck size={17} />Résoudre et vérifier les liens</button>{["treatment", "publication"].includes(tab) && <button type="button" disabled={busy || !report || report.status === "deleted" && (!metadata?.canDelete || tab === "publication")} onClick={() => tab === "publication" ? action("/publication", "POST", publication, true) : action("", "PATCH", draft, true)}><Save size={17} />Enregistrer</button>}</div>
    {resolution && <Dialog title="Confirmer la résolution" className="issue-editor-dialog" dismissible={!busy} onClose={() => setResolution(null)}><div className="issue-editor-body"><p>BUG {id} sera traité. Les doublons sont proposés ; les autres liens demandent une vérification individuelle.</p><Select label="Résultat" value={resolution.status} onChange={(status) => setResolution({ ...resolution, status })} options={{ fixed: "Corrigé", closed: "Fermé" }} /><div className="issue-resolution-list">{report.resolutionPlan.rows.map((row) => <label key={row.id} className="issue-check"><input type="checkbox" checked={resolution.linkedIds.includes(row.id)} onChange={(event) => setResolution({ ...resolution, linkedIds: event.target.checked ? [...resolution.linkedIds, row.id] : resolution.linkedIds.filter((entry) => entry !== row.id) })} /><span>BUG {row.id} · {row.title}<small>{metadata.relations[row.type]} · {metadata.statuses[row.status]}</small></span></label>)}</div><label>Réponse publique commune<textarea aria-label="Réponse publique commune" maxLength={4000} rows={3} value={resolution.response} onChange={(event) => setResolution({ ...resolution, response: event.target.value })} /></label>{error && <p className="error" role="alert">{error}</p>}</div><div className="issue-editor-footer"><button type="button" disabled={busy} onClick={async () => { if (await action("/resolution", "POST", resolution, true)) setResolution(null); }}><CheckCheck size={17} />Confirmer pour {1 + resolution.linkedIds.length} dossier(s)</button></div></Dialog>}
  </Dialog>;
}
