import { useEffect, useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import { api } from "../../api.js";

const calculationNames = { auto: "Automatique selon le jeu", duel: "Duel", ranking: "Classement complet", "winner-all": "Gagnant contre tous", teams: "Équipes" };
const exitNames = { rank: "Dernière place, sans pénalité supplémentaire", penalty: "Dernière place + pénalité redistribuée", cancel: "Annuler l’attribution Elo de la partie" };
const numericFields = [["initialElo","Elo initial",100,5000,1],["placementGames","Parties de placement (0 = désactivé)",0,25,1],["k","K après la phase provisoire",1,128,1],["d","Diviseur D",1,10000,1],["gamma","Exposant multijoueur γ",0,2,.05],["maximumVariation","Variation maximale (facultatif)",.01,10000,.01],["minimumElo","Elo minimum (facultatif)",0,5000,.01],["minimumGames","Parties avant publication au classement",0,1000,1]];
export function RankedEloSettings({ current, gameId, change, reset }) {
  const [players,setPlayers]=useState([{elo:1000,games:30,position:1,team:0,reason:"result"},{elo:1200,games:30,position:2,team:1,reason:"result"}]);
  const [results,setResults]=useState([]),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const signature=JSON.stringify({players,settings:current,gameId});
  useEffect(()=> {
    const controller=new AbortController();
    setBusy(true);
    const timer=setTimeout(()=>api("/api/admin/ranked/simulate",{method:"POST",body:signature,signal:controller.signal,background:true,deduplicate:false})
      .then((data)=>{if(!controller.signal.aborted){setResults(data.results);setError("");}})
      .catch((err)=>{if(!controller.signal.aborted){setResults([]);setError(err.message);}})
      .finally(()=>{if(!controller.signal.aborted)setBusy(false);}),300);
    return ()=>{clearTimeout(timer);controller.abort();};
  },[signature]);
  const teamMode=current.calculation==="teams" || current.calculation==="auto" && gameId==="belote";
  const updatePlayer=(index,patch)=>setPlayers((rows)=>rows.map((row,i)=>i===index?{...row,...patch}:row));
  return <div className="ranked-elo-workspace">
    <section className="ranked-elo-equation"><h3>Formule de calcul</h3><p><code>E = 1 / (1 + 10 ^ ((R adverse − R joueur) / D))</code></p><p><code>Δ = Σ [K paire × (résultat − E)] / (N − 1) ^ γ</code></p><p>K paire = moyenne des K des deux joueurs. Résultat : 1 devant, 0,5 à égalité, 0 derrière. Les équipes utilisent leur Elo moyen. Le total des variations entre joueurs déjà classés reste nul, après pénalités et arrondi.</p><p><code>Placement = Elo adverse moyen + D × log10((score + 0,5) / (parties − score + 0,5))</code></p><small>Chaque partie de placement pèse autant. Le score tient compte de la position face aux adversaires, les égalités comptent pour moitié. L’Elo officiel reste figé jusqu’au placement final ; cette attribution initiale n’est pas un transfert à somme nulle.</small>{gameId && <button type="button" className="secondary" onClick={reset}>Reprendre les valeurs communes de calcul</button>}</section>
    <section><h3>Calcul et limites</h3><div className="admin-field-grid">{numericFields.map(([key,label,min,max,step])=><label key={key}>{label}<input type="number" min={min} max={max} step={step} required={!["maximumVariation","minimumElo"].includes(key)} value={current[key]??""} onChange={(event)=>change(key,event.target.value===""?null:Number(event.target.value))}/></label>)}<label>Type de calcul<select value={current.calculation} onChange={(event)=>change("calculation",event.target.value)}>{Object.entries(calculationNames).filter(([id])=>id!=="duel" || current.maximumPlayers===2).filter(([id])=>id!=="teams" || gameId==="belote").map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Égalités<select value={current.ties} onChange={(event)=>change("ties",event.target.value)}><option value="draw">Demi-victoire (0,5)</option><option value="ignore">Ignorer les confrontations à égalité</option></select></label></div></section>
    <section><h3>Elo provisoire</h3><div className="ranked-provisional-list">{current.provisional.map((tier,index)=><div key={index}><label>Jusqu’à la partie<input aria-label={`Fin du palier provisoire ${index+1}`} type="number" min={1} max={1000} value={tier.through} onChange={(event)=>change("provisional",current.provisional.map((row,i)=>i===index?{...row,through:Number(event.target.value)}:row))}/></label><label>Coefficient K<input aria-label={`K du palier provisoire ${index+1}`} type="number" min={1} max={128} value={tier.k} onChange={(event)=>change("provisional",current.provisional.map((row,i)=>i===index?{...row,k:Number(event.target.value)}:row))}/></label><button type="button" className="secondary icon-toggle" title="Retirer le palier" aria-label={`Retirer le palier ${index+1}`} onClick={()=>change("provisional",current.provisional.filter((_,i)=>i!==index))}><Trash2 size={17}/></button></div>)}</div><button type="button" className="secondary" disabled={current.provisional.length>=10} onClick={()=>change("provisional",[...current.provisional,{through:(current.provisional.at(-1)?.through??0)+10,k:current.k}])}><Plus size={17}/>Ajouter un palier</button></section>
    <section><h3>Abandons et déconnexions</h3><div className="admin-field-grid">{[["abandonPolicy","Abandon / inactivité"],["disconnectPolicy","Déconnexion prolongée"]].map(([key,label])=><label key={key}>{label}<select value={current[key]} onChange={(event)=>change(key,event.target.value)}>{Object.entries(exitNames).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>)}{[["abandonPenalty","Pénalité d’abandon / déconnexion"],["afkPenalty","Pénalité AFK"]].map(([key,label])=><label key={key}>{label}<input type="number" min={0} max={500} value={current[key]} onChange={(event)=>change(key,Number(event.target.value))}/></label>)}</div></section>
    <section className="ranked-elo-simulator" aria-busy={busy}><h3>Simulation sans modifier les comptes</h3><div className="ranked-tier-table"><table><thead><tr><th>Joueur</th><th>Elo</th><th>Parties déjà jouées</th><th>Position finale</th>{teamMode&&<th>Équipe</th>}<th>Sortie</th><th>Variation</th><th>Après</th><th/></tr></thead><tbody>{players.map((row,index)=><tr key={index}><th>{index+1}</th>{[["elo",-100000,100000],["games",0,100000],["position",1,100]].map(([key,min,max])=><td key={key}><input aria-label={`${key} joueur ${index+1}`} type="number" min={min} max={max} value={row[key]} onChange={(event)=>updatePlayer(index,{[key]:Number(event.target.value)})}/></td>)}{teamMode&&<td><select aria-label={`Équipe joueur ${index+1}`} value={row.team} onChange={(event)=>updatePlayer(index,{team:Number(event.target.value)})}><option value={0}>Bleue</option><option value={1}>Rouge</option></select></td>}<td><select aria-label={`Sortie joueur ${index+1}`} value={row.reason} onChange={(event)=>updatePlayer(index,{reason:event.target.value})}>{[["result","Partie terminée"],["abandon","Abandon"],["disconnect","Déconnexion"],["afk","AFK"]].map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></td><td>{results[index]?`${results[index].delta>0?"+":""}${results[index].delta.toFixed(2)}`:"—"}</td><td>{results[index]?.after??"—"}</td><td><button type="button" className="secondary icon-toggle" title="Retirer le joueur" aria-label={`Retirer le joueur ${index+1}`} disabled={players.length<=2} onClick={()=>setPlayers((rows)=>rows.filter((_,i)=>i!==index))}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div><button type="button" className="secondary" disabled={players.length>=16 || current.calculation==="duel"} onClick={()=>setPlayers((rows)=>[...rows,{elo:1000,games:30,position:rows.length+1,team:rows.length%2,reason:"result"}])}><Plus size={17}/>Ajouter un joueur</button>{error?<p className="error" role="alert">{error}</p>:<p role="status">Total des variations : {(results.reduce((sum,row)=>sum+Math.round(row.delta*100),0)/100).toFixed(2)} Elo{busy?" · Calcul en cours…":""}</p>}</section>
  </div>;
}
