import { useEffect, useState } from "react";
import { AlertTriangle, Banknote, BookOpen, CheckCircle2, CircleDot, Dices, Eye, EyeOff, HelpCircle, ShieldCheck, Swords, Trophy, X } from "lucide-react";
import { Die, DiceThrowTray, PlayingCard } from "./GamePieces.jsx";
import { DisplayName } from "../cosmetics/Cosmetics.jsx";
import { battleScoringLabels, playerName, suits } from "../../features/games/config.js";
import { midnightContractEvaluation, midnightContractInfo, midnightContractLabel, midnightContractTiers, midnightScorePreview } from "../../features/games/midnightDice/model.js";
import { velvetClaimAllowed } from "../../features/games/velvetRuse/model.js";
import { farkleCombos, farkleSelectionScore, farkleSuggestions, shutTileCombinations } from "../../features/games/farkle/model.js";
import { CompactNumber, formatExactNumber } from "../../utils/presentation.jsx";

export function FarkleBoard({ state, user, onAction, rollLocked = false }) {
  const [selected, setSelected] = useState([]);
  const current = state.players[state.currentPlayerIndex];
  const isMyTurn = current?.id === user.id;
  const selectedDice = selected.map((index) => state.dice[index]).filter(Boolean);
  const preview = farkleSelectionScore(selectedDice);
  const banked = state.scores?.[user.id] ?? 0;
  const entryScore = state.modifiers?.entryScore ?? 0;
  const entryMissing = banked === 0 && state.turnScore < entryScore;
  const progress = Math.min(100, Math.round((banked / (state.target || 10000)) * 100));
  const suggestions = farkleSuggestions(state.dice);

  useEffect(() => { setSelected([]); }, [state.currentPlayerIndex, state.dice.join("-"), state.turnScore]);

  return <section className={`farkle-table ${isMyTurn ? "active" : "spectating"}`}>
    <header className="farkle-heading"><div><span className="eyebrow">Tour à risque</span><h2>{isMyTurn ? "Construis ton coup" : `${current?.pseudo ?? "Un joueur"} construit son coup`}</h2><p>Sélectionne uniquement les dés qui forment une combinaison, puis encaisse ou relance les autres.</p></div><div className="farkle-target"><span>Objectif</span><strong><CompactNumber value={state.target} suffix=" pts" label="Objectif exact" /></strong><div><i style={{ width: `${progress}%` }} /></div><small><CompactNumber value={banked} suffix=" sécurisés" label="Score sécurisé exact" /></small></div></header>
    <div className="farkle-dashboard">
      <section className="farkle-play-zone">
        <div className="farkle-score-strip"><span><small>Score sécurisé</small><strong><CompactNumber value={banked} label="Score exact" /></strong></span><span className="turn-bank"><small>En jeu ce tour</small><strong><CompactNumber value={state.turnScore} prefix="+" label="Score exact du tour" /></strong></span><span><small>Dés à relancer</small><strong>{state.remainingDice || 6}</strong></span></div>
        <div className={`farkle-dice-stage ${state.bust ? "bust" : ""}`}>
          <DiceThrowTray label="Piste de risque" caption={`${state.remainingDice || 6} dé${(state.remainingDice || 6) > 1 ? "s" : ""} disponibles`}>{(state.dice.length ? state.dice : Array(state.remainingDice || 6).fill(null)).map((die, index) => <Die key={`${index}-${die ?? "empty"}-${state.turnScore}`} value={die} kept={selected.includes(index)} selectionLabel="À marquer" skin={current?.cosmetics?.equipped?.diceSkin ?? user.cosmetics?.equipped?.diceSkin ?? "default"} onClick={isMyTurn && !state.bust ? () => setSelected((values) => values.includes(index) ? values.filter((value) => value !== index) : [...values, index]) : undefined} />)}</DiceThrowTray>
          {state.bust ? <div className="farkle-bust"><AlertTriangle /><div><strong>Aucune combinaison possible</strong><span>Les points accumulés ce tour sont perdus. Confirme le score nul pour passer la main.</span></div></div> : state.dice.length ? <div className={`farkle-selection-readout ${selected.length && !preview.valid ? "invalid" : preview.valid ? "valid" : ""}`}><CircleDot /><span><small>Sélection actuelle</small><strong>{preview.label}</strong></span><b>{preview.valid ? `+${preview.points}` : "—"}</b></div> : <div className="farkle-decision-tip"><ShieldCheck /><span><strong>{state.turnScore ? "Encaisser ou prendre le risque ?" : "Lance les six dés"}</strong><small>{state.turnScore ? "Encaisser sécurise le tour. Relancer peut tout faire perdre." : `Premier encaissement requis : ${entryScore} points.`}</small></span></div>}
        </div>
        {!state.bust && state.dice.length > 0 && suggestions.length > 0 && <div className="farkle-suggestions"><span>Combinaisons détectées</span>{suggestions.map((suggestion) => <button type="button" className={suggestion.indexes.every((index) => selected.includes(index)) && selected.length === suggestion.indexes.length ? "active" : "secondary"} disabled={!isMyTurn} onClick={() => setSelected(suggestion.indexes)} key={`${suggestion.values.join("-")}-${suggestion.points}`}><strong>{suggestion.label}</strong><small>{suggestion.values.join(" · ")} · +{suggestion.points}</small></button>)}</div>}
        <div className="farkle-actions">
          {state.bust ? <button className="danger-button" disabled={!isMyTurn} onClick={() => onAction({ type: "forfeit" })}><AlertTriangle size={18} /> Terminer le tour · 0 point</button> : <>
            <button data-request-feedback="state" aria-busy={rollLocked} className={rollLocked ? "roll-cooldown" : ""} disabled={!isMyTurn || state.dice.length > 0 || rollLocked} onClick={() => onAction({ type: "roll" })}><Dices size={18} /> Lancer {state.remainingDice || 6} dé{(state.remainingDice || 6) > 1 ? "s" : ""}</button>
            <button className="secondary" disabled={!isMyTurn || !state.dice.length || !preview.valid} onClick={() => onAction({ type: "select", indexes: selected })}>Marquer la sélection {preview.valid ? `· +${preview.points}` : ""}</button>
            <button disabled={!isMyTurn || !state.turnScore || state.dice.length > 0 || entryMissing} title={entryMissing ? `Atteins ${formatExactNumber(entryScore)} points pour entrer dans la partie` : `Sécuriser exactement ${formatExactNumber(state.turnScore)} points`} onClick={() => onAction({ type: "bank" })}><Banknote size={18} /> Encaisser <CompactNumber value={state.turnScore} /></button>
          </>}
        </div>
        {entryMissing && state.turnScore > 0 && <p className="farkle-entry-warning"><AlertTriangle size={16} /> Encore {Math.max(0, entryScore - state.turnScore)} points avant de pouvoir entrer au score.</p>}
      </section>
      <aside className="farkle-combo-guide"><div className="panel-heading"><span>Combinaisons possibles</span><small>Les combinaisons à six dés déclenchent les « dés chauds » : tu relances les six.</small></div><div className="farkle-combo-grid">{farkleCombos.map((combo) => <article key={combo.id}><div className="farkle-mini-dice">{combo.dice.map((die, index) => <Die value={die} kept={false} animate={false} skin="default" key={`${combo.id}-${index}`} />)}</div><span><strong>{combo.label}</strong><small>{combo.points}</small></span></article>)}</div></aside>
    </div>
  </section>;
}

export function LiarsDiceBoard({ state, user, onAction }) {
  const current = state.players[state.currentPlayerIndex];
  const isMyTurn = current?.id === user.id;
  const totalDice = Object.values(state.diceCounts ?? {}).reduce((sum, count) => sum + count, 0);
  const minimumBid = state.bid ? (state.bid.face < 6 ? { quantity: state.bid.quantity, face: state.bid.face + 1 } : { quantity: state.bid.quantity + 1, face: 1 }) : { quantity: 1, face: 1 };
  const [bid, setBid] = useState(minimumBid);
  const ownHand = state.hands?.[user.id] ?? [];
  const ownMatches = ownHand.filter((die) => die === bid.face).length;
  const hiddenDice = Math.max(0, totalDice - ownHand.length);
  const expected = ownMatches + hiddenDice / 6;
  const bidValid = !state.bid || bid.quantity > state.bid.quantity || (bid.quantity === state.bid.quantity && bid.face > state.bid.face);

  useEffect(() => { setBid(minimumBid); }, [state.bid?.quantity, state.bid?.face, state.round]);

  return <section className="liar-arena">
    <header className="liar-heading"><div><span className="eyebrow">Duel de bluff · Manche {state.round}</span><h2>{isMyTurn ? "À toi de prendre l’ascendant" : `${current?.pseudo ?? "Un joueur"} doit répondre`}</h2><p>Monte l’enchère ou accuse le dernier joueur de mentir. Les dés adverses restent secrets jusqu’à la contestation.</p></div><div className="liar-pool"><strong>{totalDice}</strong><span>dés encore en jeu</span></div></header>
    <div className="liar-opponents">{state.players.filter((player) => player.id !== user.id).map((player) => <article className={player.id === current?.id ? "active" : ""} key={player.id}><header><DisplayName user={player} /><span>{player.id === state.lastBidderId ? "Dernière annonce" : player.id === current?.id ? "Doit répondre" : "Observe"}</span></header><div className="liar-cup"><EyeOff size={24} /><strong>{state.diceCounts[player.id]}</strong><small>dés cachés</small></div></article>)}</div>
    <div className="liar-confrontation">
      <section className="liar-own-hand"><div className="panel-heading"><span>Ta main secrète</span><small>{ownHand.length} dé{ownHand.length > 1 ? "s" : ""} · visible uniquement par toi</small></div><DiceThrowTray compact label="Sous ton gobelet" caption="Lancer privé">{ownHand.map((die, index) => <Die key={`${index}-${die}-${state.round}`} value={die} kept={die === bid.face} selectionLabel="Correspond" skin={user.cosmetics?.equipped?.diceSkin ?? "default"} />)}</DiceThrowTray><div className="liar-read"><Eye size={17} /><span>Pour l’annonce préparée : <strong>{ownMatches}</strong> correspondance{ownMatches > 1 ? "s" : ""} certaine{ownMatches > 1 ? "s" : ""}, estimation globale <strong>≈ {expected.toFixed(1)}</strong>.</span></div></section>
      <section className="liar-bid-stage"><span className="eyebrow">Enchère sur la table</span>{state.bid ? <><div className="liar-current-bid"><strong>{state.bid.quantity}</strong><span>dé{state.bid.quantity > 1 ? "s" : ""} montrant</span><Die value={state.bid.face} kept={false} animate={false} skin={state.players.find((player) => player.id === state.lastBidderId)?.cosmetics?.equipped?.diceSkin ?? "default"} /></div><small>annoncée par {state.players.find((player) => player.id === state.lastBidderId)?.pseudo ?? "un joueur"}</small></> : <div className="liar-empty-bid"><Dices /><strong>Ouvre les enchères</strong></div>}<div className="liar-versus"><i /><Swords /><i /></div></section>
      <section className={`liar-command ${isMyTurn ? "active" : ""}`}><div className="panel-heading"><span>Ta réponse</span><small>{isMyTurn ? "Augmente la quantité ou la face" : "En attente du joueur actif"}</small></div><label className="liar-quantity">Quantité<div><button className="secondary" type="button" disabled={!isMyTurn || bid.quantity <= 1} onClick={() => setBid({ ...bid, quantity: bid.quantity - 1 })}>−</button><strong>{bid.quantity}</strong><button className="secondary" type="button" disabled={!isMyTurn || bid.quantity >= totalDice} onClick={() => setBid({ ...bid, quantity: bid.quantity + 1 })}>+</button></div></label><fieldset><legend>Face annoncée</legend><div className="liar-face-grid">{[1, 2, 3, 4, 5, 6].map((face) => <button type="button" className={bid.face === face ? "active" : ""} disabled={!isMyTurn} onClick={() => setBid({ ...bid, face })} key={face}><Die value={face} kept={false} animate={false} skin="default" /></button>)}</div></fieldset><div className="actions"><button disabled={!isMyTurn || !bidValid || bid.quantity > totalDice} onClick={() => onAction({ type: "bid", ...bid })}>Annoncer {bid.quantity} × {bid.face}</button><button className="danger-button" disabled={!isMyTurn || !state.bid} onClick={() => onAction({ type: "challenge" })}><Swords size={17} /> Menteur !</button></div>{!bidValid && <small className="invalid-bid">L’enchère doit dépasser {state.bid.quantity} × {state.bid.face}.</small>}</section>
    </div>
    {state.lastReveal && <section className="liar-reveal"><div><span className="eyebrow">Dernière confrontation</span><h3>{state.lastReveal.actual} dé{state.lastReveal.actual > 1 ? "s" : ""} de {state.lastReveal.face} révélé{state.lastReveal.actual > 1 ? "s" : ""}</h3><p>{state.players.find((player) => player.id === state.lastReveal.loserId)?.pseudo ?? "Le joueur éliminé"} perd un dé.</p></div><div>{Object.entries(state.lastReveal.hands ?? {}).map(([playerId, hand]) => <article key={playerId}><strong>{state.players.find((player) => player.id === playerId)?.pseudo ?? "Joueur"}</strong><div className="liar-reveal-dice">{hand.map((die, index) => <Die value={die} kept={die === state.lastReveal.face} selectionLabel="Compté" animate={false} skin={state.players.find((player) => player.id === playerId)?.cosmetics?.equipped?.diceSkin ?? "default"} key={`${playerId}-${index}`} />)}</div></article>)}</div></section>}
  </section>;
}

export function ShutTheBoxBoard({ state, user, onAction, rollLocked = false }) {
  const [selected, setSelected] = useState([]);
  const current = state.players[state.currentPlayerIndex];
  const isMyTurn = current?.id === user.id;
  const open = state.boxes?.[current?.id] ?? [];
  const combinations = shutTileCombinations(open, state.lastTotal);
  const selectedTotal = selected.reduce((sum, value) => sum + value, 0);
  const exact = Boolean(state.lastTotal && selectedTotal === state.lastTotal);
  const remainingScore = open.reduce((sum, value) => sum + value, 0);
  const maxTile = state.modifiers?.maxTile ?? 9;

  useEffect(() => { setSelected([]); }, [state.currentPlayerIndex, state.lastTotal, open.join("-")]);

  return <section className={`shut-table ${isMyTurn ? "active" : "spectating"}`}>
    <header className="shut-heading"><div><span className="eyebrow">Boîte de {current?.pseudo ?? "jeu"}</span><h2>{isMyTurn ? "Ferme exactement le total" : `Observe le tour de ${current?.pseudo ?? "l’adversaire"}`}</h2><p>Choisis une ou plusieurs tuiles ouvertes dont la somme correspond au lancer.</p></div><div className="shut-score"><small>Valeur encore ouverte</small><strong>{remainingScore}</strong><span>Le score le plus bas gagne</span></div></header>
    <div className="shut-player-strip">{state.players.map((player) => { const done = state.scores[player.id] !== undefined; const openScore = (state.boxes[player.id] ?? []).reduce((sum, value) => sum + value, 0); return <article className={`${player.id === current?.id ? "active" : ""} ${done ? "done" : ""}`} key={player.id}><DisplayName user={player} /><span>{done ? `${state.scores[player.id]} pts` : `${openScore} ouverts`}</span></article>; })}</div>
    <div className="shut-cabinet"><div className="shut-hinge left" /><div className="shut-hinge right" /><div className="shut-tiles">{Array.from({ length: maxTile }, (_, index) => index + 1).map((tile) => { const available = open.includes(tile); const chosen = selected.includes(tile); const appearsInCombo = combinations.some((combo) => combo.includes(tile)); return <button type="button" key={tile} className={`${available ? "open" : "closed"} ${chosen ? "selected" : ""} ${state.lastTotal && appearsInCombo ? "playable" : ""}`} disabled={!isMyTurn || !state.lastTotal || !available} onClick={() => setSelected((values) => values.includes(tile) ? values.filter((value) => value !== tile) : [...values, tile])}><span>{tile}</span><small>{available ? chosen ? "Choisie" : "Ouverte" : "Fermée"}</small></button>; })}</div></div>
    <div className="shut-console"><section className="shut-roll"><DiceThrowTray compact label="Piste de la boîte" caption="Lancer de deux dés">{(state.dice.length ? state.dice : [null, null]).map((die, index) => <Die key={`${index}-${die ?? "empty"}-${state.lastTotal ?? 0}`} value={die} kept={false} skin={current?.cosmetics?.equipped?.diceSkin ?? "default"} />)}</DiceThrowTray><div className="shut-total"><small>Total à fermer</small><strong>{state.lastTotal ?? "—"}</strong></div></section><section className="shut-choice"><div><small>Somme sélectionnée</small><strong className={selectedTotal > (state.lastTotal ?? Infinity) ? "over" : exact ? "exact" : ""}>{selected.length ? `${selected.join(" + ")} = ${selectedTotal}` : "Choisis des tuiles"}</strong></div>{state.lastTotal && combinations.length > 0 && <div className="shut-suggestions"><span>Coups possibles</span>{combinations.slice(0, 6).map((combo) => <button type="button" className="secondary" disabled={!isMyTurn} onClick={() => setSelected(combo)} key={combo.join("-")}>{combo.join(" + ")}</button>)}</div>}<div className="actions"><button data-request-feedback="state" aria-busy={rollLocked} className={rollLocked ? "roll-cooldown" : ""} disabled={!isMyTurn || Boolean(state.lastTotal) || rollLocked} onClick={() => onAction({ type: "roll" })}><Dices size={18} /> Lancer</button><button disabled={!isMyTurn || !exact} onClick={() => onAction({ type: "shut", numbers: selected })}><CheckCircle2 size={18} /> Fermer la sélection</button></div></section></div>
  </section>;
}

function BattleResolutionTimer({ endsAt, duration = 10000 }) {
  const [now, setNow] = useState(Date.now());
  useEffect(() => {
    if (!endsAt) return undefined;
    setNow(Date.now());
    const timer = setInterval(() => setNow(Date.now()), 250);
    return () => clearInterval(timer);
  }, [endsAt]);
  const remaining = Math.max(0, endsAt - now);
  const progress = Math.max(0, Math.min(100, remaining / duration * 100));
  return <section className="battle-resolution-timer" aria-live="polite"><div><span>Prochaine manche</span><strong>{Math.ceil(remaining / 1000)} s</strong></div><div className="battle-timer-track"><i style={{ width: `${progress}%` }} /></div></section>;
}

export function BattleBoard({ state, user, onDraw, onPlace }) {
  const [deckOpen, setDeckOpen] = useState(false);
  const self = state.players.find((player) => player.id === user.id) ?? user;
  const opponent = state.players.find((player) => player.id !== user.id);
  const submitted = state.submittedPlayerIds?.includes(user.id);
  const drawnCard = state.drawnCards?.[user.id];
  const resolving = Boolean(state.resolutionEndsAt);
  const forcedLane = state.battleLanes?.find((lane) => lane.tie)?.id ?? null;
  const laneLabel = (laneId) => laneId === "center" ? "Pile centrale" : laneId === "left" ? "Pile A" : "Pile B";
  const laneMarker = (laneId) => laneId === "center" ? "◆" : laneId === "left" ? "A" : "B";
  const latestEvents = state.lastResolution?.events ?? [];
  useEffect(() => { if (state.modifiers?.hiddenDeck) setDeckOpen(false); }, [state.modifiers?.hiddenDeck]);
  const playerStatus = (player) => {
    if (resolving) return "Confrontation en cours";
    if (state.submittedPlayerIds?.includes(player.id)) return "Placement verrouillé";
    const thinking = state.botThinking?.[player.id]?.phase;
    if (thinking === "draw") return "Réfléchit avant de piocher…";
    if (thinking === "place") return "Observe sa carte…";
    if (state.drawnCards?.[player.id]) return player.id === user.id ? "Carte en main" : "Carte piochée";
    return "Prêt à piocher";
  };
  const renderPlayerSide = (player, isSelf) => {
    if (!player) return null;
    const playerDrawnCard = state.drawnCards?.[player.id];
    const playerSubmitted = state.submittedPlayerIds?.includes(player.id);
    const skin = player.cosmetics?.equipped?.cardSkin ?? "default";
    const canInspectDeck = isSelf && !state.modifiers?.hiddenDeck && Boolean(state.deckOverview);
    return <section className={`battle-player-side ${isSelf ? "battle-self" : "battle-opponent"}`} key={player.id}>
      <div className="battle-player-heading"><div><small>{isSelf ? "Ton camp" : "Adversaire"}</small><strong><DisplayName user={player} /></strong></div><span className={state.botThinking?.[player.id] ? "thinking" : playerSubmitted ? "submitted" : ""}>{playerStatus(player)}</span></div>
      <div className="battle-player-layout">
        <div className="battle-deck-station">
          <div className={`battle-deck-stack ${canInspectDeck ? "inspectable" : ""}`} role={canInspectDeck ? "button" : undefined} tabIndex={canInspectDeck ? 0 : -1} title={canInspectDeck ? "Consulter l’estimation de ta pioche" : state.modifiers?.hiddenDeck && isSelf ? "Pioche cachée par les modificateurs" : undefined} onClick={() => canInspectDeck && setDeckOpen(true)} onKeyDown={(event) => { if (canInspectDeck && (event.key === "Enter" || event.key === " ")) { event.preventDefault(); setDeckOpen(true); } }}><PlayingCard hidden skin={skin} /><b>{state.piles?.[player.id]?.length ?? 0}</b><small>{canInspectDeck ? "Estimer la pioche" : "Pioche"}</small></div>
          <div className={`battle-drawn-station ${playerDrawnCard ? "has-card" : ""} ${playerSubmitted ? "submitted-card" : ""}`}>
            {playerDrawnCard ? <PlayingCard key={`drawn-${state.round}-${player.id}`} card={isSelf && !playerDrawnCard.hidden ? playerDrawnCard : null} hidden={!isSelf || Boolean(playerDrawnCard.hidden)} skin={skin} /> : playerSubmitted ? <PlayingCard key={`locked-${state.round}-${player.id}`} hidden skin={skin} /> : <div className="battle-empty-card"><small>Carte piochée</small></div>}
            <small>{playerSubmitted ? "Choix secret" : playerDrawnCard ? (isSelf ? "Ta carte" : "Carte en main") : "En attente"}</small>
          </div>
          {isSelf && !playerDrawnCard && !playerSubmitted && !resolving && <button type="button" className="battle-draw-button" disabled={!(state.piles?.[player.id]?.length ?? 0)} onClick={onDraw}>Piocher une carte</button>}
        </div>
        <div className={`battle-player-field ${state.battleLanes?.length === 1 ? "single-lane" : ""}`}>{(state.battleLanes ?? []).map((lane) => {
          const playerCards = lane.cards.filter((entry) => entry.ownerId === player.id);
          const card = playerCards.at(-1);
          const resolutionEvent = resolving ? latestEvents.find((event) => event.laneId === lane.id) : null;
          const calculation = resolutionEvent?.calculations?.[player.id];
          const cardsToShow = lane.resolving || lane.tie ? playerCards : card ? [card] : [];
          const placementDisabled = resolving || !isSelf || !drawnCard || submitted || Boolean(forcedLane && forcedLane !== lane.id);
          const showPlacementAction = isSelf && drawnCard && !submitted && !resolving;
          return <div className={`battle-placement-slot ${lane.tie ? "war-active" : ""} ${lane.resolving ? "resolving" : ""}`} key={`${player.id}-${lane.id}`}><span className="battle-lane-marker">{laneMarker(lane.id)}</span>{cardsToShow.length ? <div className="battle-card-stack">{cardsToShow.map((visibleCard, index) => <PlayingCard key={`${player.id}-${lane.id}-${visibleCard.placedRound}-${index}`} card={visibleCard.hidden ? null : visibleCard} hidden={Boolean(visibleCard.hidden)} skin={skin} style={{ "--battle-card-index": index }} />)}</div> : <div className="battle-empty-card"><small>{laneLabel(lane.id)}</small></div>}<small>{playerCards.length ? `${playerCards.length} carte${playerCards.length > 1 ? "s" : ""} engagée${playerCards.length > 1 ? "s" : ""}` : "Libre"}</small>{calculation && <div className="battle-score-calculation"><strong>{calculation.total} pts</strong><span>{calculation.label}</span>{calculation.combos?.length ? <small>{calculation.combos.join(" + ")}</small> : null}</div>}{isSelf && <button type="button" className={showPlacementAction ? "" : "battle-placement-placeholder"} disabled={!showPlacementAction || placementDisabled} tabIndex={showPlacementAction ? 0 : -1} aria-hidden={!showPlacementAction} onClick={() => onPlace(lane.id)}>{lane.tie ? `Défendre ${laneLabel(lane.id)}` : `Placer sur ${laneLabel(lane.id)}`}</button>}</div>;
        })}</div>
      </div>
    </section>;
  };
  return (
    <div className="strategic-battle">
      <div className="battle-round-heading"><div><span>Manche {state.round} · {battleScoringLabels[state.modifiers?.scoringMode] ?? battleScoringLabels["high-card"]}</span><strong>{resolving ? "Résolution de la confrontation" : submitted ? "Placement verrouillé" : drawnCard ? (forcedLane ? `Défends ${laneLabel(forcedLane)}` : state.battleLanes?.length === 1 ? "Place ta carte sur la pile centrale" : "Choisis la pile A ou B") : "Pioche ta carte"}</strong></div><small>{resolving ? "Les cartes restent sur le tapis jusqu’à la fin du décompte." : submitted ? "Ta carte et sa pile restent secrètes jusqu’à la résolution." : drawnCard ? "Tu connais ta carte; ton adversaire n’en voit que le dos." : "La pioche est une action visible, mais sa valeur reste privée."}</small></div>
      {resolving && <BattleResolutionTimer endsAt={state.resolutionEndsAt} duration={state.resolutionDurationMs} />}
      <div className="battle-mode-strip"><span><strong>{state.battleLanes?.length === 1 ? "Pile simple" : "Pile double"}</strong>{battleScoringLabels[state.modifiers?.scoringMode]}</span><span>Retour après {state.modifiers?.returnAfterRounds ?? 3} manches</span><span>{state.modifiers?.hiddenDeck ? <EyeOff size={15} /> : <Eye size={15} />} Pioche {state.modifiers?.hiddenDeck ? "cachée" : "visible"}</span></div>
      <div className="battle-table-faceoff">
        {renderPlayerSide(opponent, false)}
        <div className={`battle-confrontation-axis ${state.battleLanes?.length === 1 ? "single-lane" : ""}`}>{(state.battleLanes ?? []).map((lane) => { const event = resolving ? latestEvents.find((entry) => entry.laneId === lane.id) : null; return <div className={lane.tie ? "war-active" : lane.resolving ? "resolving" : ""} key={lane.id}><Swords size={18} /><strong>{laneLabel(lane.id)}</strong><small>{event?.type === "battle" ? `${event.calculations?.[event.winnerId]?.total ?? "—"} pts gagnants` : event?.type === "tie" ? "Égalité · Bataille" : event?.type === "return" ? "Retour à la pioche" : lane.tie ? "Bataille en cours" : lane.cards.length ? `${lane.idleRounds}/${state.modifiers?.returnAfterRounds ?? 3} sans duel` : "Zone de confrontation"}</small></div>; })}</div>
        {renderPlayerSide(self, true)}
      </div>
      {latestEvents.length > 0 && <section className="battle-resolution"><div className="panel-heading"><span>Résolution de la manche {state.lastResolution.round}</span><small>{latestEvents.length} événement{latestEvents.length > 1 ? "s" : ""}</small></div>{latestEvents.map((event, index) => <article className={`battle-event event-${event.type}`} key={`${state.lastResolution.round}-${event.laneId}-${event.type}-${index}`}><div><strong>{laneLabel(event.laneId)}</strong><span>{event.type === "battle" ? <><DisplayName user={state.players.find((player) => player.id === event.winnerId)} /> remporte {event.wonCards} carte(s) · {event.calculations?.[event.winnerId]?.label}{event.unseenWonCards ? ` · ${event.unseenWonCards} obtenue(s) non identifiée(s)` : ""}</> : event.type === "tie" ? `Égalité à ${Object.values(event.calculations ?? {})[0]?.total ?? "—"} points : ${event.stake} carte(s) restent en jeu` : event.reason === "timeout" ? `${event.count} carte(s) retournent face cachée dans la pioche après ${state.modifiers?.returnAfterRounds ?? 3} manches` : "Les cartes bloquées retournent dans les pioches"}</span></div>{resolving && event.cards && <div className="battle-revealed-cards">{state.players.map((player) => event.cards[player.id] ? <div key={player.id}><div className="battle-event-card-row">{(Array.isArray(event.cards[player.id]) ? event.cards[player.id] : [event.cards[player.id]]).map((card, cardIndex) => <PlayingCard key={`${card.rank}-${card.suit}-${cardIndex}`} card={card} skin={player.cosmetics?.equipped?.cardSkin ?? "default"} />)}</div><small>{player.pseudo}</small></div> : null)}</div>}</article>)}</section>}
      {deckOpen && state.deckOverview && <div className="modal-backdrop battle-deck-modal-layer" onClick={() => setDeckOpen(false)}><div className="modal battle-deck-modal" onClick={(event) => event.stopPropagation()}><div className="modal-title-row"><div><span className="eyebrow">Estimation de la pioche</span><h2>{state.deckOverview.total} cartes dans ton paquet</h2></div><button className="secondary icon-toggle" onClick={() => setDeckOpen(false)}><X size={18} /></button></div><p>Cette vue respecte les informations que tu as réellement obtenues. Une carte absente de la liste est connue comme impossible dans ta pioche.</p><div className="battle-deck-knowledge-summary"><span className="certain"><CheckCircle2 size={18} /><strong>{state.deckOverview.certainCount}</strong><small>Présence certaine · 100 %</small></span><span className="possible"><HelpCircle size={18} /><strong>{state.deckOverview.possibleCount}</strong><small>Présence possible</small></span><span className="impossible"><X size={18} /><small>0 % · non affichée</small></span></div>{state.deckOverview.unseenAcquiredCount > 0 && <div className="battle-acquired-note"><Trophy size={17} /><span><strong>{state.deckOverview.unseenAcquiredCount} carte{state.deckOverview.unseenAcquiredCount > 1 ? "s" : ""} obtenue{state.deckOverview.unseenAcquiredCount > 1 ? "s" : ""}</strong> lors d'une victoire, valeur encore inconnue.</span></div>}<div className="battle-deck-card-grid">{state.deckOverview.cards.map((card) => <div className={`battle-deck-probability ${card.status}`} key={`${card.rank}-${card.suit}`}><PlayingCard card={card} skin={self.cosmetics?.equipped?.cardSkin ?? "default"} /><span title={card.status === "certain" ? "Présence certaine" : "Présence possible"}>{card.status === "certain" ? <CheckCircle2 size={15} /> : "?"}</span></div>)}</div></div></div>}
    </div>
  );
}

export function MidnightDiceBoard({ state, user, onAction }) {
  const [codexOpen, setCodexOpen] = useState(false);
  const current = state.players[state.currentPlayerIndex];
  const isMyTurn = current?.id === user.id;
  const ownContract = state.secretContracts?.[user.id];
  const usedContracts = state.usedContracts?.[user.id] ?? [];
  const marketSkin = current?.cosmetics?.equipped?.diceSkin ?? user.cosmetics?.equipped?.diceSkin ?? "default";
  const contracts = (state.contractOffers ?? Object.keys(midnightContractInfo).slice(0, 4)).map((id) => [id, midnightContractInfo[id]]).filter(([, info]) => info);
  const currentContract = midnightContractInfo[ownContract];
  const currentTier = midnightContractTiers[currentContract?.tier] ?? midnightContractTiers.bronze;
  const ownDice = state.trays?.[user.id] ?? [];
  const currentEvaluation = midnightContractEvaluation(ownContract, ownDice);
  const tierEntries = Object.entries(midnightContractTiers).sort(([, left], [, right]) => left.order - right.order);
  return <section className="midnight-table">
    <header className="midnight-heading"><div><span className="eyebrow">Salle des mandats</span><h2>Dés de Minuit</h2><p>Manche {state.round} / {state.modifiers.rounds}</p></div><div className="midnight-heading-actions"><button type="button" className="secondary midnight-codex-button" onClick={() => setCodexOpen(true)}><BookOpen size={17} /> Voir les 12 mandats</button><div className={`midnight-phase phase-${state.phase}`}><small>{state.phase === "contract" ? "Mandat secret" : "Marché ouvert"}</small><strong>{isMyTurn ? "À toi de décider" : `${current?.pseudo ?? "Le croupier"} réfléchit`}</strong></div></div></header>
    <div className="midnight-player-trays">{state.players.map((player) => { const dice = state.trays?.[player.id] ?? []; const isSelf = player.id === user.id; return <article className={`${player.id === current?.id ? "active" : ""} ${isSelf ? "self" : ""}`} key={player.id}><header><DisplayName user={player} /><strong>{state.scores?.[player.id] ?? 0} pts</strong></header><div className="midnight-tray-dice">{[0, 1, 2].map((index) => <div className="midnight-die-slot" key={index}>{dice[index] ? <Die value={dice[index]} kept={false} skin={player.cosmetics?.equipped?.diceSkin ?? "default"} /> : <span>{index + 1}</span>}</div>)}</div><footer><span>{isSelf && ownContract ? midnightContractLabel(ownContract) : state.phase === "contract" ? "Choix en cours" : "Mandat masqué"}</span>{isSelf && ownContract && <b>Projection {midnightScorePreview(ownContract, dice)} pts</b>}</footer></article>; })}</div>
    {currentContract && <aside className="midnight-current-contract" style={{ "--contract-accent": currentTier.accent }}><div><EyeOff size={22} /><span><small>Ton mandat en cours</small><strong>{currentContract.label}</strong></span><b className="midnight-tier-badge">{currentTier.label}</b></div><p>{currentContract.hint}</p><div><span>{ownDice.length} / 3 dés · base {currentEvaluation.base}</span><b>{ownDice.length === 3 ? currentEvaluation.achieved ? `${currentEvaluation.base} + ${currentEvaluation.bonus} = ${currentEvaluation.points} points` : `${currentEvaluation.points} points · mandat manqué` : `Prime de réussite +${currentTier.bonus}`}</b></div></aside>}
    {state.phase === "contract" && <div className={`midnight-contract-room midnight-contract-prompt ${isMyTurn ? "active" : "waiting"}`}><div><span className="eyebrow">Mandat secret</span><strong>{isMyTurn ? "Choisis ton objectif pour cette manche" : `${current?.pseudo ?? "Un joueur"} choisit son mandat`}</strong><small>Les quatre propositions restent secrètes jusqu’à la résolution.</small></div><div className="midnight-offer-preview" aria-label="Paliers proposés">{contracts.map(([id, info]) => { const tier = midnightContractTiers[info.tier]; return <span style={{ "--contract-accent": tier.accent }} title={`${tier.label} · ${midnightContractLabel(id)}`} key={id}><i />{tier.label}</span>; })}</div><button type="button" disabled={!isMyTurn} onClick={() => setCodexOpen(true)}><BookOpen size={18} /> {isMyTurn ? "Choisir mon mandat" : "Choix en attente"}</button></div>}
    {state.phase === "draft" && <div className="midnight-market"><div className="midnight-market-head"><div><span className="eyebrow">Marché commun</span><h3>{state.market.length} dés disponibles</h3></div><div><strong>{state.discardRemaining?.[user.id] ?? 0}</strong><small>défausse(s) restante(s)</small></div></div><div className="midnight-market-throw"><span className="midnight-market-table-label">Piste commune · dés lancés pour la manche</span><div className="midnight-market-grid">{state.market.map((die, index) => <article key={`${state.round}-${index}-${die}`} style={{ "--market-die-rotation": `${[-3, 5, -6, 3, 7, -4][index % 6]}deg` }}><Die value={die} kept={false} skin={marketSkin} /><div>{isMyTurn ? <><button onClick={() => onAction({ type: "draft", index })}>Prendre</button><button className="secondary" disabled={(state.discardRemaining?.[user.id] ?? 0) <= 0} onClick={() => onAction({ type: "discard-market", index })}>Écarter</button></> : <span>Disponible</span>}</div></article>)}</div></div>{state.discardTray?.length > 0 && <div className="midnight-discard-strip"><span>Derniers dés écartés</span>{state.discardTray.slice(-6).map((entry, index) => <b key={`${entry.playerId}-${index}`}>{entry.die} → {entry.replacement}</b>)}</div>}</div>}
    {state.lastRound && <div className="midnight-reveal"><div className="panel-heading"><span>Résultat de la manche {state.lastRound.round}</span><small>Les mandats sont désormais publics.</small></div><div>{state.lastRound.results.map((result) => { const info = midnightContractInfo[result.contract]; const evaluation = result.achieved === undefined ? midnightContractEvaluation(result.contract, result.dice) : result; const tier = midnightContractTiers[evaluation.tier ?? info?.tier] ?? midnightContractTiers.bronze; return <article className={evaluation.achieved ? "achieved" : "missed"} style={{ "--contract-accent": tier.accent }} key={result.playerId}><DisplayName user={state.players.find((player) => player.id === result.playerId)} /><span><b>{tier.label}</b> · {midnightContractLabel(result.contract)} · {result.dice.join("–")} · {evaluation.achieved ? `base ${evaluation.base} + prime ${evaluation.bonus}` : "mandat manqué"}</span><strong>+{evaluation.points}</strong></article>; })}</div></div>}
    {codexOpen && <div className="modal-backdrop midnight-codex-layer" onClick={() => setCodexOpen(false)}><div className="modal midnight-codex-modal" onClick={(event) => event.stopPropagation()}><div className="modal-title-row"><div><span className="eyebrow">{state.phase === "contract" && isMyTurn ? "Sélection secrète" : "Archives de la table"}</span><h2>{state.phase === "contract" && isMyTurn ? "Choisis ton mandat" : "Codex des mandats"}</h2><p>Chaque lancer rapporte sa somme. Réussir le mandat ajoute la prime de son palier.</p></div><button type="button" className="secondary icon-toggle" aria-label="Fermer" onClick={() => setCodexOpen(false)}><X size={18} /></button></div><div className="midnight-tier-legend">{tierEntries.map(([id, tier]) => <span className={`tier-${id}`} style={{ "--contract-accent": tier.accent }} key={id}><i /><strong>{tier.label}</strong><small>+{tier.bonus} pts</small></span>)}</div><div className="midnight-codex-groups">{tierEntries.map(([tierId, tier]) => { const entries = Object.entries(midnightContractInfo).filter(([, info]) => info.tier === tierId); if (!entries.length) return null; return <section style={{ "--contract-accent": tier.accent }} key={tierId}><header><span className="midnight-tier-badge">{tier.label}</span><strong>Prime +{tier.bonus}</strong><small>{entries.length} mandat{entries.length > 1 ? "s" : ""}</small></header><div>{entries.map(([id, info]) => { const example = midnightContractEvaluation(id, info.example); const offered = contracts.some(([contractId]) => contractId === id); const used = usedContracts.includes(id); const unavailable = state.modifiers.uniqueContracts && usedContracts.length < contracts.length && used; const selectable = state.phase === "contract" && isMyTurn && offered && !unavailable; return <article className={`${offered ? "offered" : ""} ${unavailable ? "used" : ""}`} key={id}><div><strong>{info.label}</strong><small>{info.hint}</small></div><div className="midnight-codex-example">{info.example.map((value, index) => <Die value={value} kept={false} animate={false} skin="default" key={`${id}-${index}`} />)}</div><footer><span>{offered ? unavailable ? "Rotation actuelle · utilisé" : "Disponible maintenant" : "Hors rotation"}</span><b>{example.base} + {tier.bonus} = {example.points} pts</b>{selectable && <button type="button" onClick={() => { setCodexOpen(false); onAction({ type: "choose-contract", contract: id }); }}>Choisir</button>}</footer></article>; })}</div></section>; })}</div></div></div>}
  </section>;
}

export function VelvetRuseBoard({ state, user, onAction }) {
  const [selectedCard, setSelectedCard] = useState(null);
  const [claim, setClaim] = useState({ rank: state.edict?.rank ?? "A", suit: state.edict?.suit ?? "S" });
  const current = state.players[state.currentPlayerIndex];
  const isMyTurn = current?.id === user.id;
  const hand = state.hands?.[user.id] ?? [];
  const cardSkin = user.cosmetics?.equipped?.cardSkin ?? "default";
  const ranks = ["2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K", "A"];
  const claimAllowed = velvetClaimAllowed(claim, state.edict, state.modifiers?.claimRule);
  useEffect(() => {
    setSelectedCard(null);
    setClaim({ rank: state.edict?.rank ?? "A", suit: state.edict?.suit ?? "S" });
  }, [state.currentPlayerIndex, state.phase, state.edict?.rank, state.edict?.suit]);
  const phaseLabel = state.phase === "decision" ? "Verdict" : state.phase === "draw" ? "Pioche" : "Déclaration";
  return <section className="velvet-table card-game-arena">
    <header className="velvet-heading"><div><span className="eyebrow">Salon confidentiel</span><h2>Velours Noir</h2></div><div className={`velvet-turn phase-${state.phase}`}><small>{phaseLabel}</small><strong>{isMyTurn ? "Ta décision" : `${current?.pseudo ?? "Un joueur"} joue`}</strong></div></header>
    <div className="velvet-opponents">{state.players.filter((player) => player.id !== user.id).map((player) => <article className={player.id === current?.id ? "active" : ""} key={player.id}><DisplayName user={player} /><div className="velvet-opponent-hand">{Array.from({ length: Math.min(4, state.hands?.[player.id]?.length ?? 0) }, (_, index) => <PlayingCard hidden key={index} skin={player.cosmetics?.equipped?.cardSkin ?? "default"} />)}</div><small>{state.hands?.[player.id]?.length ?? 0} cartes · <b>{state.prestige?.[player.id] ?? 0}</b> prestige</small></article>)}</div>
    <div className="velvet-center"><div className="velvet-card-station"><span>Pioche</span><button type="button" disabled={!isMyTurn || state.phase !== "draw" || !state.deck.length} onClick={() => onAction({ type: "draw", source: "deck" })}><PlayingCard hidden skin={cardSkin} /><b>{state.deck.length}</b></button></div><div className="velvet-edict"><span>Carte d'influence</span><PlayingCard card={state.edict} skin={cardSkin} /><strong>{state.modifiers?.claimRule === "suit-only" ? `Annonce ${suits[state.edict?.suit]?.name}` : state.modifiers?.claimRule === "rank-only" ? `Annonce un ${state.edict?.rank}` : `Même rang ou ${suits[state.edict?.suit]?.name}`}</strong></div><div className="velvet-dossier"><span>Dossier sous scellés</span><div>{Array.from({ length: state.modifiers?.dossierSize ?? 6 }, (_, index) => { const entry = state.dossier?.[index]; return <div className={entry ? "filled" : ""} key={index}>{entry ? <><PlayingCard hidden skin={state.players.find((player) => player.id === entry.playerId)?.cosmetics?.equipped?.cardSkin ?? cardSkin} /><small>{entry.claim.rank}{suits[entry.claim.suit]?.symbol}</small></> : <b>{index + 1}</b>}</div>; })}</div><strong>{state.dossier?.length ?? 0} / {state.modifiers?.dossierSize ?? 6} avant audit</strong></div><div className="velvet-card-station discard"><span>Défausse</span><button type="button" disabled={!isMyTurn || state.phase !== "draw" || !state.modifiers?.openDiscardDraw || !state.discard?.length} onClick={() => onAction({ type: "draw", source: "discard" })}><PlayingCard card={state.discard?.at(-1)} hidden={!state.discard?.length} skin={cardSkin} /><b>{state.modifiers?.openDiscardDraw ? "Récupérer" : "Fermée"}</b></button></div></div>
    {state.pendingClaim && <div className="velvet-pending"><div><EyeOff size={22} /><span><small>{playerName(state.players, state.pendingClaim.playerId)} annonce</small><strong>{state.pendingClaim.claim.rank}{suits[state.pendingClaim.claim.suit]?.symbol} · {suits[state.pendingClaim.claim.suit]?.name}</strong></span></div>{isMyTurn && state.phase === "decision" ? <div className="actions"><button onClick={() => onAction({ type: "trust" })}>Faire confiance</button><button className="danger-button" onClick={() => onAction({ type: "challenge" })}>Contester</button></div> : <span>Décision en attente</span>}</div>}
    <div className={`velvet-self ${isMyTurn ? "active" : ""}`}><header><div><span className="eyebrow">Ta main</span><h3>{state.prestige?.[user.id] ?? 0} / {state.modifiers?.targetPrestige ?? 20} prestige</h3></div><small>{state.phase === "play" && isMyTurn ? "Choisis une carte, puis défausse-la ou annonce-la." : state.phase === "draw" && isMyTurn ? "Choisis ta source de pioche." : state.phase === "decision" && isMyTurn ? "Lis la déclaration avant de décider." : "Observe le tour en cours."}</small></header><div className="velvet-hand">{hand.map((card, index) => <button type="button" className={selectedCard === index ? "selected" : ""} disabled={!isMyTurn || state.phase !== "play"} onClick={() => setSelectedCard(index)} key={`${card?.deckId ?? 0}-${card?.rank}-${card?.suit}-${index}`}><PlayingCard card={card} skin={cardSkin} /><span>{selectedCard === index ? "Sélectionnée" : "Choisir"}</span></button>)}</div>{isMyTurn && state.phase === "play" && <div className="velvet-play-console"><div className="velvet-claim-fields"><label>Rang annoncé<select value={claim.rank} onChange={(event) => setClaim({ ...claim, rank: event.target.value })}>{ranks.map((rank) => <option key={rank}>{rank}</option>)}</select></label><label>Enseigne annoncée<select value={claim.suit} onChange={(event) => setClaim({ ...claim, suit: event.target.value })}>{Object.entries(suits).map(([id, suit]) => <option value={id} key={id}>{suit.symbol} {suit.name}</option>)}</select></label><span className={claimAllowed ? "valid" : "invalid"}>{claimAllowed ? "Annonce conforme" : "Ne respecte pas l'influence"}</span></div><div className="actions"><button disabled={selectedCard === null || !claimAllowed} onClick={() => onAction({ type: "declare", cardIndex: selectedCard, claimRank: claim.rank, claimSuit: claim.suit })}>Glisser face cachée</button><button className="secondary" disabled={selectedCard === null} onClick={() => onAction({ type: "discard", cardIndex: selectedCard })}>Défausser face visible</button></div></div>}</div>
    {state.lastChallenge && <div className={`velvet-reveal ${state.lastChallenge.truthful ? "truth" : "lie"}`}><strong>{state.lastChallenge.truthful ? "Déclaration exacte" : "Bluff démasqué"}</strong><span>{state.lastChallenge.claim.rank}{suits[state.lastChallenge.claim.suit]?.symbol} annoncé · {state.lastChallenge.actual.rank}{suits[state.lastChallenge.actual.suit]?.symbol} révélé</span></div>}
    {state.lastAudit?.entries?.length > 0 && <div className="velvet-audit"><span>Dernier audit</span><div>{state.lastAudit.entries.map((entry, index) => <article className={entry.truthful ? "truth" : "lie"} key={`${entry.playerId}-${index}`}><PlayingCard card={entry.actual} skin={state.players.find((player) => player.id === entry.playerId)?.cosmetics?.equipped?.cardSkin ?? cardSkin} /><small>{entry.truthful ? "+1 exact" : "−2 bluff"}</small></article>)}</div></div>}
  </section>;
}
