import { ArrowLeft, Coins, Mail, ShieldCheck } from "lucide-react";
import { appPath } from "../navigation/routes.js";
import { legalLinks } from "./Privacy.jsx";

const email = "contact@netdis.org";
const contact = <a href={`mailto:${email}`}>{email}</a>;
const documents = {
  parents: {
    intro: "Un parcours accompagné pour les joueurs de moins de 13 ans, sans paiement ni collecte automatique de documents d'identité.",
    sections: [
      ["comprendre", "Avant d'autoriser l'inscription", <><p>Les jeux sont gratuits et utilisent des jetons sans valeur réelle. Ils reprennent certains codes visuels du casino. Prenez le temps de vérifier que ces jeux conviennent à votre enfant.</p><p>Le pseudo, les résultats et les éléments choisis du profil peuvent être visibles par les autres joueurs. Choisissez un pseudonyme non identifiant, évitez les informations personnelles et convenez ensemble de limites de temps.</p></>],
      ["demander", "1. La demande d'inscription", <><p>Le formulaire demande l'adresse email d'un parent ou responsable légal lorsque la date de naissance indique moins de 13 ans. Aucun compte actif n'est créé à ce stade.</p><p>Un code de dossier unique est transmis au parent et à l'équipe. N'envoyez jamais de mot de passe ou de pièce d'identité par email sans demande explicite et explication préalable.</p></>],
      ["verifier", "2. Accord du parent et revue humaine", <><p>Le parent ouvre le lien personnel reçu, consulte les protections et donne son accord explicite. L'équipe examine ensuite le dossier avant de créer le compte.</p><p>Une validation d'adresse email ne remplace pas à elle seule la revue. L'inscription reste en attente tant que les deux étapes ne sont pas terminées.</p></>],
      ["suivre", "3. L'espace parent", <><p>Après approbation, un lien personnel donne accès à l'activité quotidienne agrégée : temps actif, sessions, pages utilisées, actions et parties terminées. Le contenu des saisies, les messages privés et les cartes cachées ne sont pas collectés pour ce récapitulatif.</p><p>Un email quotidien résume cette activité. Des rappels sont envoyés 30, 7 et 1 jour avant le treizième anniversaire, lorsque les limitations automatiques vont être levées.</p></>],
      ["retirer", "Suspendre ou réactiver l'accès", <><p>Depuis l'espace parent, l'accès peut être suspendu pour une durée choisie ou jusqu'aux 13 ans. Les sessions ouvertes sont fermées et l'enfant voit uniquement le motif et le temps restant.</p><p>L'enfant peut demander une réactivation par email. Le parent conserve la décision finale depuis son espace. Pour une rectification, un effacement ou une difficulté, contactez {contact} avec le code du dossier.</p></>]
    ]
  },
  terms: {
    intro: "Des cartes, des dés et le plaisir de jouer ensemble. Voici les règles communes à toutes les tables.",
    sections: [
      ["esprit", "Un loisir gratuit", <><p>Le site propose des mini-jeux inspirés du casino, avec des cartes, des dés et des jetons virtuels. L'accès aux jeux est gratuit.</p><p>Les jetons ne s'achètent pas avec de l'argent réel. Ils ne peuvent être retirés, convertis en argent, revendus ni échangés contre des biens ou des prix ayant une valeur réelle. Les objets de la boutique sont uniquement des personnalisations virtuelles.</p></>],
      ["compte", "Votre compte", <><p>Choisissez un pseudo respectueux et gardez votre mot de passe confidentiel. N'utilisez pas le compte d'une autre personne. Signalez un accès suspect à {contact}.</p><p>Le site n'est pas réservé aux adultes. Avant 13 ans, l'inscription exige l'email et l'accord d'un responsable légal puis une validation de l'équipe. Certaines fonctions peuvent rester limitées jusqu'au treizième anniversaire.</p></>],
      ["respect", "Jouer ensemble", <><p>Les insultes, le harcèlement, les discriminations, les contenus illicites, l'usurpation d'identité et la publication d'informations privées d'autrui ne sont pas acceptés.</p><p>N'exploitez pas les bugs, les comptes multiples ou des automatismes pour fausser les parties, les succès ou les classements. Un organisateur peut exclure un joueur de sa table. L'éditeur peut modérer un contenu ou suspendre un compte en cas d'abus ; vous pouvez demander des explications ou contester une décision par courriel.</p></>],
      ["tribunal", "Signalements et tribunal des joueurs", <><p>Un joueur peut signaler un comportement en décrivant des faits et, lorsqu'il était présent, joindre le contexte vérifié d'une table. Les signalements ne sont pas publics. Ils sont vérifiés par l'équipe ou regroupés par une règle automatique fondée sur le nombre de signalants distincts.</p><p>Les jurés reçoivent des dossiers aléatoires sans identité du signalant et votent de 1 à 5. Leur vote produit une recommandation ou une restriction sociale temporaire. Un bannissement complet ou définitif exige toujours une confirmation humaine. L'équipe peut classer, corriger ou annuler un dossier en cas d'erreur, de fraude ou d'éléments insuffisants. Toute personne sanctionnée peut demander un réexamen à {contact}.</p></>],
      ["parties", "Parties et progression", <><p>Les règles propres à chaque jeu sont accessibles dans son interface. Les succès, bonus et classements servent au divertissement et ne constituent aucune promesse de gain réel.</p><p>Le service peut être interrompu pour maintenance ou incident. Un bug peut nécessiter la correction d'un score, d'un solde ou d'un classement. Prévenez l'éditeur si une anomalie vous concerne. Faites des pauses et ne laissez pas le jeu empiéter sur vos autres activités.</p></>],
      ["contenus", "Contenus et évolution", <><p>Ne publiez que des contenus que vous avez le droit d'utiliser. Vous autorisez leur affichage dans le cadre du fonctionnement du site, sans transfert de propriété. Les marques et créations de tiers restent la propriété de leurs titulaires.</p><p>Ces conditions peuvent évoluer. Les modifications importantes seront annoncées sur le site. Le droit belge s'applique, sans priver les utilisateurs des protections impératives qui leur sont applicables. Pour toute difficulté, contactez d'abord l'éditeur afin de rechercher une solution amiable.</p></>]
    ]
  },
  legal: {
    intro: "Qui développe le site, où il est hébergé et comment nous contacter.",
    sections: [
      ["editeur", "Éditeur et responsable du site", <><dl className="legal-details"><dt>Identité</dt><dd>Sean « Bnmkt » Ferrara</dd><dt>Statut</dt><dd>Particulier</dd><dt>Contact</dt><dd>{contact}</dd><dt>Cadre juridique annoncé</dt><dd>Belgique</dd></dl><p>L'adresse postale de l'éditeur n'est pas publiée à ce stade. Le contact disponible est l'adresse électronique ci-dessus.</p></>],
      ["hebergement", "Deux hébergements distincts", <><h3>Interface web</h3><p>Hébergée chez OVHcloud. Les coordonnées du fournisseur sont disponibles dans ses <a href="https://www.ovhcloud.com/fr/terms-and-conditions/" target="_blank" rel="noreferrer">mentions légales</a>.</p><h3>Serveur de jeu et données des comptes</h3><p>Auto-hébergés et administrés par Sean Ferrara. Pour les incidents de fonctionnement et les demandes relatives aux données personnelles, utilisez {contact}.</p></>],
      ["signalement", "Signaler un problème", <><p>Indiquez la page concernée, la date approximative et une description du problème. Pour un contenu illicite, précisez son emplacement afin qu'il puisse être examiné. N'envoyez jamais votre mot de passe.</p><p>Les droits des titulaires de marques et des créateurs des éléments utilisés sur le site restent réservés.</p></>]
    ]
  },
  privacy: {
    intro: "Les données utiles au jeu, celles qui restent facultatives et les moyens de garder la main.",
    sections: [
      ["responsable", "Qui traite vos données ?", <p>Sean Ferrara, éditeur particulier du site, est responsable des traitements décrits ici. Toute question ou demande peut être adressée à {contact}.</p>],
      ["donnees", "Ce que le site utilise", <div className="legal-table-wrap"><table><thead><tr><th>Données</th><th>À quoi servent-elles ?</th><th>Fondement</th></tr></thead><tbody><tr><td>Adresse email, pseudo, mot de passe haché, session</td><td>Créer, identifier, valider et protéger votre compte</td><td>Fourniture du service demandé</td></tr><tr><td>Date de naissance, email du parent, décision et code du dossier</td><td>Calculer l’âge et gérer le parcours parental</td><td>Protection des joueurs mineurs et autorisation parentale</td></tr><tr><td>Activité quotidienne agrégée des moins de 13 ans</td><td>Informer le responsable légal et lui permettre de gérer l’accès</td><td>Protection du mineur et exécution du parcours parental</td></tr><tr><td>Identifiant aléatoire du navigateur et signal réseau haché temporaire</td><td>Limiter le contournement immédiat du parcours parental</td><td>Intérêt légitime de protection, avec rétention limitée</td></tr><tr><td>Parties, jetons, inventaire, succès, amis et invitations</td><td>Jouer et conserver votre progression</td><td>Fourniture du service demandé</td></tr><tr><td>Messages des canaux global, de table et entre amis</td><td>Permettre les échanges sociaux et assurer leur modération ; conservation maximale de 180 jours</td><td>Fourniture du service et intérêt légitime à protéger les joueurs</td></tr><tr><td>Signalements, contexte de table, votes et décisions de modération</td><td>Examiner les abus, protéger les joueurs et permettre un recours</td><td>Intérêt légitime à assurer la sécurité et l’intégrité du service</td></tr><tr><td>Profil facultatif, jeux favoris et personnalisation</td><td>Afficher les informations que vous choisissez de partager</td><td>Fonctionnalités demandées par le joueur</td></tr><tr><td>Erreurs et journaux techniques</td><td>Sécurité, diagnostic et stabilité</td><td>Intérêt légitime à protéger le service</td></tr><tr><td>Types de pages, famille du navigateur, indices autorisés, temps actif</td><td>Succès facultatifs liés à la navigation</td><td>Votre consentement, retirable</td></tr></tbody></table></div>],
      ["visibilite", "Ce qui est visible par les autres", <><p>Le pseudo affiché, la member card, les statistiques et éléments du profil public peuvent être vus par les autres joueurs. Les informations optionnelles que vous publiez peuvent donc révéler des détails personnels : évitez les coordonnées, votre école et les données sensibles.</p><p>L’adresse email, le mot de passe et sa représentation hachée ne sont pas publics. La date de naissance complète reste privée ; seul l’âge calculé peut être affiché sur le profil public. Les administrateurs accèdent aux données nécessaires à la gestion et à la modération.</p></>],
      ["facultatif", "La navigation reste facultative", <><p>Le suivi des succès de navigation est désactivé avant votre choix. Il utilise uniquement des catégories de pages, des compteurs de temps actif sur le site, à une table et dans une manche, des jours de visite, une famille de navigateur et des indices de jeu prévus dans les paramètres « secret » ou « challenge » des liens.</p><p>Il ne collecte pas l'URL complète, les mots de passe présents dans des liens, l'historique externe, la géolocalisation ou une empreinte de votre appareil. Les indices sont évalués sans archivage des requêtes de navigation. Les compteurs sont rattachés à votre compte : ils ne sont pas anonymes.</p><p>Un refus n'empêche ni de jouer ni de gagner des jetons. Un retrait arrête ce suivi ; après synchronisation avec le serveur, les compteurs facultatifs et la progression correspondante sont effacés. Les succès déjà obtenus restent acquis. Ce suivi n'est pas activable avant 13 ans dans le parcours actuel.</p></>],
      ["bugs", "Signaler un bug sans exposer ses données", <><p>Le formulaire transmet les informations et les captures que vous choisissez de joindre. Aucun diagnostic technique n'est recueilli pour ce signalement sans votre accord explicite. Cet accord active temporairement des écouteurs d'erreur ; le retirer efface les informations recueillies dans l'onglet.</p><p>Le diagnostic comprend la version, la date, la famille et la version majeure du navigateur, le système, les dimensions d'écran, l'identifiant de compte et des codes d'erreur limités. Les messages bruts, mots de passe, cookies, tokens et contenus des requêtes sont exclus. Le diagnostic est accessible aux administrateurs et éditeurs pour la résolution du problème et supprimé après 90 jours.</p><p>Le dossier original reste privé. Seuls des textes relus et des images explicitement sélectionnées peuvent être publiés. Vérifiez vos captures avant envoi. Les signalements du compte sont inclus dans son export de données ; la suppression du compte efface ses dossiers privés, ses captures et ses diagnostics. Les versions publiques relues peuvent rester disponibles, sans lien avec le compte.</p></>],
      ["conservation", "Durées et destinataires", <><p>Le compte et la progression restent conservés tant que le compte existe, sous réserve d'une demande d'effacement et des éventuelles nécessités légales ou de sécurité. Les données d'activité parentale détaillées sont purgées après 120 jours. Le signal pseudonymisé anti-contournement bloque une nouvelle tentative pendant 7 jours.</p><p>Le choix de confidentialité est valable 180 jours. Les journaux techniques de l'application ont une rétention maximale de 14 jours et une limite de volume. L'hébergement et les sauvegardes peuvent avoir des journaux ou durées distincts ; contactez l'éditeur pour les modalités applicables.</p><p>L'interface est hébergée chez OVHcloud, le serveur de jeu est auto-hébergé. Les données ne sont pas destinées à la revente ni au ciblage publicitaire.</p></>],
      ["droits", "Vos droits et votre contact", <><p>Vous pouvez demander l'accès à vos données, leur rectification, leur effacement, la limitation du traitement, et, lorsque les conditions légales sont réunies, leur portabilité ou vous opposer à certains traitements. Retirer un consentement ne remet pas en cause les traitements effectués avant son retrait.</p><p>Dans Profil → Compte → Carte et confidentialité, vous pouvez demander une copie des données conservées dans les bases applicatives. Après une revue administrative, elle est envoyée en ZIP à votre adresse vérifiée. Le suivi affiche la demande et son échéance. Pour compléter cette copie, pour des données conservées ailleurs ou si vous n’avez plus accès au compte, écrivez à {contact}, en indiquant votre compte et votre demande. Une vérification proportionnée de votre identité peut être nécessaire, sans jamais communiquer votre mot de passe par email. Dans le site uniquement, votre mot de passe actuel confirme la demande d’envoi. La réponse intervient sans retard injustifié et au plus tard sous un mois calendaire ; une prolongation motivée de deux mois supplémentaires au maximum doit vous être annoncée dans le premier mois, dans les cas prévus par le RGPD.</p><p>Vous pouvez aussi contacter l'<a href="https://www.autoriteprotectiondonnees.be/citoyen/agir/introduire-une-plainte" target="_blank" rel="noreferrer">Autorité belge de protection des données</a>.</p></>]
    ]
  },
  cookies: {
    intro: "Pas de publicité à accepter pour jouer. Les stockages nécessaires et le suivi facultatif ont des rôles distincts.",
    sections: [
      ["necessaires", "Les stockages nécessaires", <><p>Le site utilise principalement le stockage local du navigateur, et non uniquement des cookies. Les mêmes exigences de transparence s'appliquent à ces technologies.</p><dl className="legal-details"><dt>ktgame-token</dt><dd>Maintient votre connexion. Supprimé à la déconnexion ; la validité de la session est limitée par le serveur (7 jours par défaut).</dd><dt>ktga-registration-device</dt><dd>Identifiant aléatoire utilisé pour empêcher un contournement immédiat du parcours moins de 13 ans. Il ne lit aucun identifiant matériel.</dd><dt>ktga-dice-selection-mode</dt><dd>Mémorise votre préférence de sélection des dés, jusqu'à modification ou nettoyage du stockage.</dd><dt>ktga-social-mode / ktga-social-window</dt><dd>Conserve uniquement le mode d’affichage et les dimensions de la fenêtre Social sur cet appareil.</dd><dt>ktga-exclusion:…</dt><dd>Évite de répéter un message d'exclusion dans la même session d'onglet.</dd><dt>ktga-privacy-choice</dt><dd>Mémorise l'acceptation ou le refus du suivi facultatif pendant 180 jours.</dd></dl></>],
      ["optionnels", "Les succès de navigation", <><p>Avec votre accord, des signaux limités sont envoyés au serveur pour les défis de visite, de navigateur, d'indices secrets et de temps actif. Aucun traceur publicitaire ni outil tiers d'analyse n'est ajouté par cette fonctionnalité.</p><p>Le temps actif exige un onglet visible, au premier plan et une interaction récente. Plusieurs onglets ne multiplient pas ce temps. Le site ne cherche pas à mesurer votre activité sur d'autres sites.</p></>],
      ["bugs", "Le suivi de vos signalements", <><p>Lors d'un signalement sans compte, le stockage de session « ktga-issue-receipts » conserve une clé d'accès privée pour retrouver vos derniers dossiers dans le même onglet. Elle n'identifie ni votre machine ni votre activité sur d'autres sites ; elle disparaît à la fermeture de l'onglet ou au changement de compte après connexion.</p><p>Le formulaire de bug propose séparément un diagnostic facultatif. Les écouteurs d'erreur ne sont activés qu'après cet accord explicite et sont arrêtés lors de son retrait ou de l'envoi.</p></>],
      ["choix", "Changer d'avis", <><p>Utilisez « Mes préférences » en bas de chaque page. Accepter et refuser le suivi facultatif sont deux choix possibles ; refuser ne bloque pas les jeux. Pour ce suivi, une confirmation d'âge d'au moins 13 ans est demandée, sans imposer de date de naissance.</p><p>Si vous effacez les données du navigateur ou si le choix expire, il sera redemandé. Le retrait doit être synchronisé avec le serveur ; en cas d'échec, un message vous invite à réessayer. Vous pouvez également supprimer les stockages depuis les réglages du navigateur, ce qui peut vous déconnecter.</p></>]
    ]
  }
};

export function LegalPage({ view, siteName, onBack }) {
  const document = documents[view];
  return <main className="legal-page">
    <header className="legal-heading"><button type="button" className="secondary" onClick={onBack}><ArrowLeft size={17} />Retour au casino</button><span className="eyebrow">{siteName} · Informations</span><h1>{legalLinks[view]}</h1><p>{document.intro}</p><div className="legal-facts"><span><Coins size={17} />Aucun argent réel</span><span><ShieldCheck size={17} />Choix de confidentialité</span><span>Version du 1 octobre 2026</span></div></header>
    <div className="legal-layout"><aside><nav aria-label="Sommaire">{document.sections.map(([id, title], index) => <a key={id} href={`#${id}`}><span>{String(index + 1).padStart(2, "0")}</span>{title}</a>)}</nav><a className="legal-contact" href={`mailto:${email}`}><Mail size={17} />Contacter l'éditeur</a></aside><article>{document.sections.map(([id, title, content], index) => <section id={id} key={id}><span className="eyebrow">{String(index + 1).padStart(2, "0")}</span><h2>{title}</h2>{content}</section>)}</article></div>
  </main>;
}
