import { ArrowLeft, Coins, Mail, ShieldCheck } from "lucide-react";
import { appPath } from "../navigation/routes.js";
import { legalLinks } from "./Privacy.jsx";

const email = "sean.ferrara@outlook.be";
const contact = <a href={`mailto:${email}`}>{email}</a>;
const documents = {
  parents: {
    intro: "Un parcours accompagné pour les joueurs de moins de 13 ans, sans paiement ni collecte automatique de documents d'identité.",
    sections: [
      ["comprendre", "Avant d'autoriser l'inscription", <><p>Les jeux sont gratuits et utilisent des jetons sans valeur réelle. Ils reprennent certains codes visuels du casino. Prenez le temps de vérifier que ces jeux conviennent à votre enfant.</p><p>Le pseudo, les résultats et les éléments choisis du profil peuvent être visibles par les autres joueurs. Choisissez un pseudonyme non identifiant, évitez les informations personnelles et convenez ensemble de limites de temps.</p></>],
      ["demander", "1. Le parent contacte l'éditeur", <><p>Écrivez à {contact} avec pour objet « Autorisation parentale ». Indiquez que vous souhaitez accompagner l'inscription d'un enfant de moins de 13 ans. N'envoyez pas spontanément de pièce d'identité, de date de naissance complète ou d'informations sensibles sur l'enfant.</p><p>Consultez les <a href={appPath("terms")}>conditions d'utilisation</a> et les <a href={appPath("privacy")}>informations sur les données</a> avant votre demande.</p></>],
      ["verifier", "2. Une vérification humaine", <><p>L'éditeur vous recontacte pour vérifier de manière proportionnée votre qualité de représentant légal et votre autorisation explicite, notamment pour les fonctions de profil public. Un simple courriel de demande ou une case cochée ne suffit pas à lui seul.</p><p>Les modalités de vérification, les éléments strictement nécessaires et leur conservation vous sont expliqués avant leur collecte. Aucune inscription de moins de 13 ans n'est ouverte sans cette validation.</p></>],
      ["inscrire", "3. Un code pour créer le compte", <><p>Après validation, un code à usage unique vous est remis. Il expire après 72 heures. Lors de l'inscription, choisissez « Moins de 13 ans », saisissez ce code puis accompagnez la création du compte. Ne partagez pas le code publiquement.</p><p>Le suivi facultatif des succès de navigation reste désactivé pour ce compte, même après l'autorisation parentale. Les fonctions de jeu et de progression restent disponibles.</p></>],
      ["retirer", "Retirer l'autorisation ou demander de l'aide", <><p>Contactez {contact} en indiquant la référence du dossier parental et le pseudo du compte. Vous pouvez demander la suspension du compte, la rectification ou l'effacement des données dans les conditions prévues par le RGPD.</p><p>Le lien entre le compte, la référence du dossier et la validation est conservé pour justifier l'autorisation. Les preuves de vérification sont gérées séparément par l'éditeur ; elles ne sont pas affichées sur le profil public.</p></>]
    ]
  },
  terms: {
    intro: "Des cartes, des dés et le plaisir de jouer ensemble. Voici les règles communes à toutes les tables.",
    sections: [
      ["esprit", "Un loisir gratuit", <><p>Le site propose des mini-jeux inspirés du casino, avec des cartes, des dés et des jetons virtuels. L'accès aux jeux est gratuit.</p><p>Les jetons ne s'achètent pas avec de l'argent réel. Ils ne peuvent être retirés, convertis en argent, revendus ni échangés contre des biens ou des prix ayant une valeur réelle. Les objets de la boutique sont uniquement des personnalisations virtuelles.</p></>],
      ["compte", "Votre compte", <><p>Choisissez un pseudo respectueux et gardez votre mot de passe confidentiel. N'utilisez pas le compte d'une autre personne. Signalez un accès suspect à {contact}.</p><p>Le site n'est pas réservé aux adultes. Si vous êtes mineur, parlez de votre utilisation à votre représentant légal et ne communiquez pas d'informations personnelles dans votre pseudo ou votre biographie. Avant 13 ans, contactez l'éditeur avec votre représentant légal avant de créer un compte : aucun parcours automatique de vérification parentale n'est actuellement disponible.</p></>],
      ["respect", "Jouer ensemble", <><p>Les insultes, le harcèlement, les discriminations, les contenus illicites, l'usurpation d'identité et la publication d'informations privées d'autrui ne sont pas acceptés.</p><p>N'exploitez pas les bugs, les comptes multiples ou des automatismes pour fausser les parties, les succès ou les classements. Un organisateur peut exclure un joueur de sa table. L'éditeur peut modérer un contenu ou suspendre un compte en cas d'abus ; vous pouvez demander des explications ou contester une décision par courriel.</p></>],
      ["parties", "Parties et progression", <><p>Les règles propres à chaque jeu sont accessibles dans son interface. Les succès, bonus et classements servent au divertissement et ne constituent aucune promesse de gain réel.</p><p>Le service peut être interrompu pour maintenance ou incident. Un bug peut nécessiter la correction d'un score, d'un solde ou d'un classement. Prévenez l'éditeur si une anomalie vous concerne. Faites des pauses et ne laissez pas le jeu empiéter sur vos autres activités.</p></>],
      ["contenus", "Contenus et évolution", <><p>Ne publiez que des contenus que vous avez le droit d'utiliser. Vous autorisez leur affichage dans le cadre du fonctionnement du site, sans transfert de propriété. Les marques et créations de tiers restent la propriété de leurs titulaires.</p><p>Ces conditions peuvent évoluer. Les modifications importantes seront annoncées sur le site. Le droit belge s'applique, sans priver les utilisateurs des protections impératives qui leur sont applicables. Pour toute difficulté, contactez d'abord l'éditeur afin de rechercher une solution amiable.</p></>]
    ]
  },
  legal: {
    intro: "Qui développe le site, où il est hébergé et comment nous contacter.",
    sections: [
      ["editeur", "Éditeur et responsable du site", <><dl className="legal-details"><dt>Identité</dt><dd>Sean « Bnmkt » Ferrara</dd><dt>Statut</dt><dd>Particulier</dd><dt>Contact</dt><dd>{contact}</dd><dt>Cadre juridique annoncé</dt><dd>Belgique</dd></dl><p>L'adresse postale de l'éditeur n'est pas publiée à ce stade. Le contact disponible est l'adresse électronique ci-dessus.</p></>],
      ["hebergement", "Deux hébergements distincts", <><h3>Interface web</h3><p>Hébergée chez OVHcloud. Les coordonnées du fournisseur sont disponibles dans ses <a href="https://www.ovhcloud.com/fr/terms-and-conditions/" target="_blank" rel="noreferrer">mentions légales</a>.</p><h3>Serveur de jeu et données des comptes</h3><p>Auto-hébergés et administrés par Sean Ferrara. Pour les incidents de fonctionnement et les demandes relatives aux données personnelles, utilisez {contact}.</p></>],
      ["signalement", "Signaler un problème", <><p>Indiquez la page concernée, la date approximative et une description du problème. Pour un contenu illicite, précisez son emplacement afin qu'il puisse être examiné. N'envoyez jamais votre mot de passe.</p><p>Les droits des titulaires de marques et des créateurs des éléments utilisés sur le site restent réservés.</p></>]
    ]
  },
  privacy: {
    intro: "Les données utiles au jeu, celles qui restent facultatives et les moyens de garder la main.",
    sections: [
      ["responsable", "Qui traite vos données ?", <p>Sean Ferrara, éditeur particulier du site, est responsable des traitements décrits ici. Toute question ou demande peut être adressée à {contact}.</p>],
      ["donnees", "Ce que le site utilise", <div className="legal-table-wrap"><table><thead><tr><th>Données</th><th>À quoi servent-elles ?</th><th>Fondement</th></tr></thead><tbody><tr><td>Identifiant, pseudo, mot de passe haché, session</td><td>Créer et protéger votre compte</td><td>Fourniture du service demandé</td></tr><tr><td>Parties, jetons, inventaire, succès, amis et invitations</td><td>Jouer et conserver votre progression</td><td>Fourniture du service demandé</td></tr><tr><td>Profil facultatif, jeux favoris et personnalisation</td><td>Afficher les informations que vous choisissez de partager</td><td>Fonctionnalités demandées par le joueur</td></tr><tr><td>Erreurs et journaux techniques</td><td>Sécurité, diagnostic et stabilité</td><td>Intérêt légitime à protéger le service</td></tr><tr><td>Types de pages, famille du navigateur, indices autorisés, temps actif</td><td>Succès facultatifs liés à la navigation</td><td>Votre consentement, retirable</td></tr></tbody></table></div>],
      ["visibilite", "Ce qui est visible par les autres", <><p>Le pseudo affiché, la member card, les statistiques et éléments du profil public peuvent être vus par les autres joueurs. Les informations optionnelles que vous publiez peuvent donc révéler des détails personnels : évitez les coordonnées, votre école et les données sensibles.</p><p>Le mot de passe et sa représentation hachée ne sont pas publics. La date de naissance, si renseignée, sert notamment au calcul de l'âge ; vérifiez les informations affichées sur votre profil public. Les administrateurs accèdent aux données nécessaires à la gestion et à la modération.</p></>],
      ["facultatif", "La navigation reste facultative", <><p>Le suivi des succès de navigation est désactivé avant votre choix. Il utilise uniquement des catégories de pages, des compteurs de temps actif et de jours de visite, une famille de navigateur et des indices de jeu prévus dans les paramètres « secret » ou « challenge » des liens.</p><p>Il ne collecte pas l'URL complète, les mots de passe présents dans des liens, l'historique externe, la géolocalisation ou une empreinte de votre appareil. Les indices sont évalués sans archivage des requêtes de navigation. Les compteurs sont rattachés à votre compte : ils ne sont pas anonymes.</p><p>Un refus n'empêche ni de jouer ni de gagner des jetons. Un retrait arrête ce suivi ; après synchronisation avec le serveur, les compteurs facultatifs et la progression correspondante sont effacés. Les succès déjà obtenus restent acquis. Ce suivi n'est pas activable avant 13 ans dans le parcours actuel.</p></>],
      ["conservation", "Durées et destinataires", <><p>Le compte et la progression restent conservés tant que le compte existe, sous réserve d'une demande d'effacement et des éventuelles nécessités légales ou de sécurité. Il n'existe pas encore de purge automatique des comptes inactifs. Les compteurs facultatifs restent conservés jusqu'au retrait du suivi ou à la suppression du compte.</p><p>Le choix de confidentialité est valable 180 jours. Les journaux techniques de l'application ont une rétention maximale de 14 jours et une limite de volume. L'hébergement et les sauvegardes peuvent avoir des journaux ou durées distincts ; contactez l'éditeur pour les modalités applicables.</p><p>L'interface est hébergée chez OVHcloud, le serveur de jeu est auto-hébergé. Les données ne sont pas destinées à la revente ni au ciblage publicitaire. Les prestataires techniques peuvent traiter les données de connexion nécessaires à l'hébergement ; les lieux précis d'hébergement et les éventuels transferts doivent être confirmés auprès de l'éditeur.</p></>],
      ["droits", "Vos droits et votre contact", <><p>Vous pouvez demander l'accès à vos données, leur rectification, leur effacement, la limitation du traitement, et, lorsque les conditions légales sont réunies, leur portabilité ou vous opposer à certains traitements. Retirer un consentement ne remet pas en cause les traitements effectués avant son retrait.</p><p>Écrivez à {contact}, en indiquant votre compte et votre demande. Une vérification proportionnée de votre identité peut être nécessaire, sans jamais demander votre mot de passe. Une réponse est normalement apportée sous un mois, avec prolongation motivée dans les cas prévus par le RGPD.</p><p>Vous pouvez aussi contacter l'<a href="https://www.autoriteprotectiondonnees.be/citoyen/agir/introduire-une-plainte" target="_blank" rel="noreferrer">Autorité belge de protection des données</a>.</p></>]
    ]
  },
  cookies: {
    intro: "Pas de publicité à accepter pour jouer. Les stockages nécessaires et le suivi facultatif ont des rôles distincts.",
    sections: [
      ["necessaires", "Les stockages nécessaires", <><p>Le site utilise principalement le stockage local du navigateur, et non uniquement des cookies. Les mêmes exigences de transparence s'appliquent à ces technologies.</p><dl className="legal-details"><dt>ktgame-token</dt><dd>Maintient votre connexion. Supprimé à la déconnexion ; la validité de la session est limitée par le serveur (7 jours par défaut).</dd><dt>ktga-dice-selection-mode</dt><dd>Mémorise votre préférence de sélection des dés, jusqu'à modification ou nettoyage du stockage.</dd><dt>ktga-exclusion:…</dt><dd>Évite de répéter un message d'exclusion dans la même session d'onglet.</dd><dt>ktga-privacy-choice</dt><dd>Mémorise l'acceptation ou le refus du suivi facultatif pendant 180 jours.</dd></dl></>],
      ["optionnels", "Les succès de navigation", <><p>Avec votre accord, des signaux limités sont envoyés au serveur pour les défis de visite, de navigateur, d'indices secrets et de temps actif. Aucun traceur publicitaire ni outil tiers d'analyse n'est ajouté par cette fonctionnalité.</p><p>Le temps actif exige un onglet visible, au premier plan et une interaction récente. Plusieurs onglets ne multiplient pas ce temps. Le site ne cherche pas à mesurer votre activité sur d'autres sites.</p></>],
      ["choix", "Changer d'avis", <><p>Utilisez « Mes préférences » en bas de chaque page. Accepter et refuser le suivi facultatif sont deux choix possibles ; refuser ne bloque pas les jeux. Pour ce suivi, une confirmation d'âge d'au moins 13 ans est demandée, sans imposer de date de naissance.</p><p>Si vous effacez les données du navigateur ou si le choix expire, il sera redemandé. Le retrait doit être synchronisé avec le serveur ; en cas d'échec, un message vous invite à réessayer. Vous pouvez également supprimer les stockages depuis les réglages du navigateur, ce qui peut vous déconnecter.</p></>]
    ]
  }
};

export function LegalPage({ view, siteName, onBack }) {
  const document = documents[view];
  return <main className="legal-page">
    <header className="legal-heading"><button type="button" className="secondary" onClick={onBack}><ArrowLeft size={17} />Retour au casino</button><span className="eyebrow">{siteName} · Informations</span><h1>{legalLinks[view]}</h1><p>{document.intro}</p><div className="legal-facts"><span><Coins size={17} />Aucun argent réel</span><span><ShieldCheck size={17} />Choix de confidentialité</span><span>Version du 27 septembre 2026</span></div></header>
    <div className="legal-layout"><aside><nav aria-label="Sommaire">{document.sections.map(([id, title], index) => <a key={id} href={`#${id}`}><span>{String(index + 1).padStart(2, "0")}</span>{title}</a>)}</nav><a className="legal-contact" href={`mailto:${email}`}><Mail size={17} />Contacter l'éditeur</a></aside><article>{document.sections.map(([id, title, content], index) => <section id={id} key={id}><span className="eyebrow">{String(index + 1).padStart(2, "0")}</span><h2>{title}</h2>{content}</section>)}</article></div>
  </main>;
}
